<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pengaturan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pengaturan_model');
        if (!isset($this->session->userdata['logged_in'])) {
            header("Location:" .base_url("login"));
        } 
    } 

    /*
     * Listing of pengaturan
     */
    function index()
    {
        $data['pengaturan'] = $this->Pengaturan_model->get_all_pengaturan();

        $data['_view'] = 'pengaturan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pengaturan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tahun_aktif' => $this->input->post('tahun_aktif'),
            );
            
            $pengaturan_id = $this->Pengaturan_model->add_pengaturan($params);
            redirect('pengaturan/index');
        }
        else
        {            
            $data['_view'] = 'pengaturan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pengaturan
     */
    function edit($id)
    {   
        // check if the pengaturan exists before trying to edit it
        $data['pengaturan'] = $this->Pengaturan_model->get_pengaturan($id);
        
        if(isset($data['pengaturan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tahun_aktif' => $this->input->post('tahun_aktif'),
                );

                $this->Pengaturan_model->update_pengaturan($id,$params);            
                redirect('pengaturan/index');
            }
            else
            {
                $data['_view'] = 'pengaturan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pengaturan you are trying to edit does not exist.');
    } 

    /*
     * Deleting pengaturan
     */
    function remove($id)
    {
        $pengaturan = $this->Pengaturan_model->get_pengaturan($id);

        // check if the pengaturan exists before trying to delete it
        if(isset($pengaturan['id']))
        {
            $this->Pengaturan_model->delete_pengaturan($id);
            redirect('pengaturan/index');
        }
        else
            show_error('The pengaturan you are trying to delete does not exist.');
    }
    
}
