<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pptk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pptk_model');
        if (!isset($this->session->userdata['logged_in'])) {
            header("Location:" .base_url("login"));
        }         
    } 

    /*
     * Listing of pptk
     */
    function index()
    {
        $data['pptk'] = $this->Pptk_model->get_all_pptk();

        $data['_view'] = 'pptk/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pptk
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_pptk' => $this->input->post('nama_pptk'),
				'kode_pd' => $this->input->post('kode_pd'),
				'jabat_pptk' => $this->input->post('jabat_pptk'),
				'foto_pptk' => $this->input->post('foto_pptk'),
				'update_tgl' => $this->input->post('update_tgl'),
				'update_oleh' => $this->input->post('update_oleh'),
            );
            
            $pptk_id = $this->Pptk_model->add_pptk($params);
            redirect('pptk/index');
        }
        else
        {            
            $data['_view'] = 'pptk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pptk
     */
    function edit($nip_pptk)
    {   
        // check if the pptk exists before trying to edit it
        $data['pptk'] = $this->Pptk_model->get_pptk($nip_pptk);
        
        if(isset($data['pptk']['nip_pptk']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_pptk' => $this->input->post('nama_pptk'),
					'kode_pd' => $this->input->post('kode_pd'),
					'jabat_pptk' => $this->input->post('jabat_pptk'),
					'foto_pptk' => $this->input->post('foto_pptk'),
					'update_tgl' => $this->input->post('update_tgl'),
					'update_oleh' => $this->input->post('update_oleh'),
                );

                $this->Pptk_model->update_pptk($nip_pptk,$params);            
                redirect('pptk/index');
            }
            else
            {
                $data['_view'] = 'pptk/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pptk you are trying to edit does not exist.');
    } 

    /*
     * Deleting pptk
     */
    function remove($nip_pptk)
    {
        $pptk = $this->Pptk_model->get_pptk($nip_pptk);

        // check if the pptk exists before trying to delete it
        if(isset($pptk['nip_pptk']))
        {
            $this->Pptk_model->delete_pptk($nip_pptk);
            redirect('pptk/index');
        }
        else
            show_error('The pptk you are trying to delete does not exist.');
    }
    
}
