<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Laporan_kota_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_daftar_pd($tahun_anggaran)
    {
      $sql = '
        SELECT 
          d.kode_pd,
          d.nama_pd,
          d.kode_prog_btl,
          d.kode_giat_btl,
          SUM(a.pagu_giat) AS anggaran_total,
          SUM(IF(b.kode_giat = d.kode_giat_btl, a.pagu_giat, 0)) AS anggaran_btl,
          SUM(IF(b.kode_giat <> d.kode_giat_btl OR d.kode_giat_btl = "" OR d.kode_giat_btl IS NULL, a.pagu_giat, 0)) AS anggaran_bl
          FROM belanja AS a
          JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
          JOIN program AS c ON b.kode_prog = c.kode_prog
          JOIN pd AS d ON c.kode_pd = d.kode_pd
          GROUP BY d.kode_pd
          ORDER BY d.kode_pd';
      $query = $this->db->query($sql);
      return $query->result();
    }

function get_total_target_realisasi_kota($tahun_anggaran)
    {
      $sql = '
        SELECT 
          SUM(a.pagu_giat) AS anggaran_total,
          SUM(IF(b.kode_giat = d.kode_giat_btl, a.pagu_giat, 0)) AS anggaran_btl,
          SUM(IF(b.kode_giat <> d.kode_giat_btl OR d.kode_giat_btl = "" OR d.kode_giat_btl IS NULL, a.pagu_giat, 0)) AS anggaran_bl        
          FROM belanja AS a
          JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
          JOIN program AS c ON b.kode_prog = c.kode_prog
          JOIN pd AS d ON c.kode_pd = d.kode_pd';
      $query = $this->db->query($sql);
      $tabel_kota = $query->result_array()[0];
      // hitung persen BL dan BTL
      $tabel_kota["anggaran_bl_persen"] = ($tabel_kota["anggaran_bl"] / $tabel_kota["anggaran_total"])*100;
      $tabel_kota["anggaran_btl_persen"] = ($tabel_kota["anggaran_btl"] / $tabel_kota["anggaran_total"])*100;

      $sql = '
        SELECT 
          COUNT(DISTINCT a.kode_rek_belanja) AS jumlah_belanja,
          COUNT(DISTINCT b.kode_giat) AS jumlah_kegiatan,
          COUNT(DISTINCT c.kode_prog) AS jumlah_program      
          FROM belanja AS a
          JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
          JOIN program AS c ON b.kode_prog = c.kode_prog
          JOIN pd AS d ON c.kode_pd = d.kode_pd
          WHERE b.kode_giat <> d.kode_giat_btl OR d.kode_giat_btl = "" OR d.kode_giat_btl IS NULL';
      $query = $this->db->query($sql);
      $jlh = $query->result_array()[0];
      $tabel_kota["jumlah_program"] = $jlh["jumlah_program"];
      $tabel_kota["jumlah_kegiatan"] = $jlh["jumlah_kegiatan"];
      $tabel_kota["jumlah_belanja"] = $jlh["jumlah_belanja"];

      $sql = '
        SELECT 
          d.kode_pd,
          SUM(a.pagu_giat) AS anggaran_total,
          SUM(IF(b.kode_giat = d.kode_giat_btl, a.pagu_giat, 0)) AS anggaran_btl,
          SUM(IF(b.kode_giat <> d.kode_giat_btl OR d.kode_giat_btl = "" OR d.kode_giat_btl IS NULL, a.pagu_giat, 0)) AS anggaran_bl,
          d.tf_1,d.tf_2,d.tf_3,d.tf_4,d.tf_5,d.tf_6,d.tf_7,d.tf_8,d.tf_9,d.tf_10,d.tf_11,d.tf_12,
          d.tk_1,d.tk_2,d.tk_3,d.tk_4,d.tk_5,d.tk_6,d.tk_7,d.tk_8,d.tk_9,d.tk_10,d.tk_11,d.tk_12,
          d.btl_tf_1,d.btl_tf_2,d.btl_tf_3,d.btl_tf_4,d.btl_tf_5,d.btl_tf_6,d.btl_tf_7,d.btl_tf_8,d.btl_tf_9,d.btl_tf_10,d.btl_tf_11,d.btl_tf_12,
          d.btl_tk_1,d.btl_tk_2,d.btl_tk_3,d.btl_tk_4,d.btl_tk_5,d.btl_tk_6,d.btl_tk_7,d.btl_tk_8,d.btl_tk_9,d.btl_tk_10,d.btl_tk_11,d.btl_tk_12,
          d.btl_rf_1,d.btl_rf_2,d.btl_rf_3,d.btl_rf_4,d.btl_rf_5,d.btl_rf_6,d.btl_rf_7,d.btl_rf_8,d.btl_rf_9,d.btl_rf_10,d.btl_rf_11,d.btl_rf_12,
          d.btl_rk_1,d.btl_rk_2,d.btl_rk_3,d.btl_rk_4,d.btl_rk_5,d.btl_rk_6,d.btl_rk_7,d.btl_rk_8,d.btl_rk_9,d.btl_rk_10,d.btl_rk_11,d.btl_rk_12          
          FROM belanja AS a
          JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
          JOIN program AS c ON b.kode_prog = c.kode_prog
          JOIN pd AS d ON c.kode_pd = d.kode_pd
          GROUP BY d.kode_pd
          ORDER BY d.kode_pd';
      $query = $this->db->query($sql);
      $tabel_pd = $query->result_array();

      $i = 0;
      foreach ($tabel_pd as $pd) {
          $sql = '
            SELECT 
              a.kode_rek_belanja,
              a.pagu_giat,
              a.kf_1,a.kf_2,a.kf_3,a.kf_4,a.kf_5,a.kf_6,a.kf_7,a.kf_8,a.kf_9,a.kf_10,a.kf_11,a.kf_12,
              a.kk_1,a.kk_2,a.kk_3,a.kk_4,a.kk_5,a.kk_6,a.kk_7,a.kk_8,a.kk_9,a.kk_10,a.kk_11,a.kk_12,
              IF(b.kode_giat = d.kode_giat_btl, "btl", "bl") AS bl_btl
              FROM belanja AS a
              JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
              JOIN program AS c ON b.kode_prog = c.kode_prog
              JOIN pd AS d ON c.kode_pd = d.kode_pd
              WHERE d.kode_pd = "'.$pd["kode_pd"].'"';
          $query = $this->db->query($sql);
          $tabel_pd_tertentu = $query->result_array(); 
          // inisialisasi variabel Realisasi Fisik dan Keuangan
          $realisasi_fisik_pd_1     = 0.0;
          $realisasi_fisik_pd_2     = 0.0;
          $realisasi_fisik_pd_3     = 0.0;
          $realisasi_fisik_pd_4     = 0.0;
          $realisasi_fisik_pd_5     = 0.0;
          $realisasi_fisik_pd_6     = 0.0;
          $realisasi_fisik_pd_7     = 0.0;
          $realisasi_fisik_pd_8     = 0.0;
          $realisasi_fisik_pd_9     = 0.0;
          $realisasi_fisik_pd_10    = 0.0;
          $realisasi_fisik_pd_11    = 0.0;
          $realisasi_fisik_pd_12    = 0.0;
          $realisasi_keuangan_pd_1  = 0;
          $realisasi_keuangan_pd_2  = 0;
          $realisasi_keuangan_pd_3  = 0;
          $realisasi_keuangan_pd_4  = 0;
          $realisasi_keuangan_pd_5  = 0;
          $realisasi_keuangan_pd_6  = 0;
          $realisasi_keuangan_pd_7  = 0;
          $realisasi_keuangan_pd_8  = 0;
          $realisasi_keuangan_pd_9  = 0;
          $realisasi_keuangan_pd_10 = 0;
          $realisasi_keuangan_pd_11 = 0;
          $realisasi_keuangan_pd_12 = 0;

          foreach ($tabel_pd_tertentu as $pdt) {
              if ($pdt["bl_btl"] == "bl"){
                  $realisasi_fisik_pd_1     = $realisasi_fisik_pd_1     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_1"]);
                  $realisasi_fisik_pd_2     = $realisasi_fisik_pd_2     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_2"]);
                  $realisasi_fisik_pd_3     = $realisasi_fisik_pd_3     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_3"]);
                  $realisasi_fisik_pd_4     = $realisasi_fisik_pd_4     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_4"]);
                  $realisasi_fisik_pd_5     = $realisasi_fisik_pd_5     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_5"]);
                  $realisasi_fisik_pd_6     = $realisasi_fisik_pd_6     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_6"]);
                  $realisasi_fisik_pd_7     = $realisasi_fisik_pd_7     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_7"]);
                  $realisasi_fisik_pd_8     = $realisasi_fisik_pd_8     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_8"]);
                  $realisasi_fisik_pd_9     = $realisasi_fisik_pd_9     + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_9"]);
                  $realisasi_fisik_pd_10    = $realisasi_fisik_pd_10    + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_10"]);
                  $realisasi_fisik_pd_11    = $realisasi_fisik_pd_11    + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_11"]);
                  $realisasi_fisik_pd_12    = $realisasi_fisik_pd_12    + (($pdt["pagu_giat"] / $pd["anggaran_bl"]) * $pdt["kf_12"]);

                  $realisasi_keuangan_pd_1  = $realisasi_keuangan_pd_1  + $pdt["kk_1"];
                  $realisasi_keuangan_pd_2  = $realisasi_keuangan_pd_2  + $pdt["kk_2"];
                  $realisasi_keuangan_pd_3  = $realisasi_keuangan_pd_3  + $pdt["kk_3"];
                  $realisasi_keuangan_pd_4  = $realisasi_keuangan_pd_4  + $pdt["kk_4"];
                  $realisasi_keuangan_pd_5  = $realisasi_keuangan_pd_5  + $pdt["kk_5"];
                  $realisasi_keuangan_pd_6  = $realisasi_keuangan_pd_6  + $pdt["kk_6"];
                  $realisasi_keuangan_pd_7  = $realisasi_keuangan_pd_7  + $pdt["kk_7"];
                  $realisasi_keuangan_pd_8  = $realisasi_keuangan_pd_8  + $pdt["kk_8"];
                  $realisasi_keuangan_pd_9  = $realisasi_keuangan_pd_9  + $pdt["kk_9"];
                  $realisasi_keuangan_pd_10 = $realisasi_keuangan_pd_10 + $pdt["kk_10"];
                  $realisasi_keuangan_pd_11 = $realisasi_keuangan_pd_11 + $pdt["kk_11"];
                  $realisasi_keuangan_pd_12 = $realisasi_keuangan_pd_12 + $pdt["kk_12"];
              }
          }

          // Buat array Tabel PD

          $tabel_pd[$i]["kf_1"] = $realisasi_fisik_pd_1 ; 
          $tabel_pd[$i]["kf_2"] = $realisasi_fisik_pd_2 ; 
          $tabel_pd[$i]["kf_3"] = $realisasi_fisik_pd_3 ; 
          $tabel_pd[$i]["kf_4"] = $realisasi_fisik_pd_4 ; 
          $tabel_pd[$i]["kf_5"] = $realisasi_fisik_pd_5 ; 
          $tabel_pd[$i]["kf_6"] = $realisasi_fisik_pd_6 ; 
          $tabel_pd[$i]["kf_7"] = $realisasi_fisik_pd_7 ; 
          $tabel_pd[$i]["kf_8"] = $realisasi_fisik_pd_8 ; 
          $tabel_pd[$i]["kf_9"] = $realisasi_fisik_pd_9 ; 
          $tabel_pd[$i]["kf_10"] = $realisasi_fisik_pd_10; 
          $tabel_pd[$i]["kf_11"] = $realisasi_fisik_pd_11; 
          $tabel_pd[$i]["kf_12"] = $realisasi_fisik_pd_12;  

          $tabel_pd[$i]["kk_1"] = $realisasi_keuangan_pd_1 ; 
          $tabel_pd[$i]["kk_2"] = $realisasi_keuangan_pd_2 ; 
          $tabel_pd[$i]["kk_3"] = $realisasi_keuangan_pd_3 ; 
          $tabel_pd[$i]["kk_4"] = $realisasi_keuangan_pd_4 ; 
          $tabel_pd[$i]["kk_5"] = $realisasi_keuangan_pd_5 ; 
          $tabel_pd[$i]["kk_6"] = $realisasi_keuangan_pd_6 ; 
          $tabel_pd[$i]["kk_7"] = $realisasi_keuangan_pd_7 ; 
          $tabel_pd[$i]["kk_8"] = $realisasi_keuangan_pd_8 ; 
          $tabel_pd[$i]["kk_9"] = $realisasi_keuangan_pd_9 ; 
          $tabel_pd[$i]["kk_10"] = $realisasi_keuangan_pd_10; 
          $tabel_pd[$i]["kk_11"] = $realisasi_keuangan_pd_11; 
          $tabel_pd[$i]["kk_12"] = $realisasi_keuangan_pd_12;          
          $i++;
      }    

      $target_bl_fisik_kota_1     = 0.0;
      $target_bl_fisik_kota_2     = 0.0;
      $target_bl_fisik_kota_3     = 0.0;
      $target_bl_fisik_kota_4     = 0.0;
      $target_bl_fisik_kota_5     = 0.0;
      $target_bl_fisik_kota_6     = 0.0;
      $target_bl_fisik_kota_7     = 0.0;
      $target_bl_fisik_kota_8     = 0.0;
      $target_bl_fisik_kota_9     = 0.0;
      $target_bl_fisik_kota_10    = 0.0;
      $target_bl_fisik_kota_11    = 0.0;
      $target_bl_fisik_kota_12    = 0.0;
      $target_bl_keuangan_kota_1  = 0;
      $target_bl_keuangan_kota_2  = 0;
      $target_bl_keuangan_kota_3  = 0;
      $target_bl_keuangan_kota_4  = 0;
      $target_bl_keuangan_kota_5  = 0;
      $target_bl_keuangan_kota_6  = 0;
      $target_bl_keuangan_kota_7  = 0;
      $target_bl_keuangan_kota_8  = 0;
      $target_bl_keuangan_kota_9  = 0;
      $target_bl_keuangan_kota_10 = 0;
      $target_bl_keuangan_kota_11 = 0;
      $target_bl_keuangan_kota_12 = 0;

      $target_btl_fisik_kota_1     = 0.0;
      $target_btl_fisik_kota_2     = 0.0;
      $target_btl_fisik_kota_3     = 0.0;
      $target_btl_fisik_kota_4     = 0.0;
      $target_btl_fisik_kota_5     = 0.0;
      $target_btl_fisik_kota_6     = 0.0;
      $target_btl_fisik_kota_7     = 0.0;
      $target_btl_fisik_kota_8     = 0.0;
      $target_btl_fisik_kota_9     = 0.0;
      $target_btl_fisik_kota_10    = 0.0;
      $target_btl_fisik_kota_11    = 0.0;
      $target_btl_fisik_kota_12    = 0.0;
      $target_btl_keuangan_kota_1  = 0;
      $target_btl_keuangan_kota_2  = 0;
      $target_btl_keuangan_kota_3  = 0;
      $target_btl_keuangan_kota_4  = 0;
      $target_btl_keuangan_kota_5  = 0;
      $target_btl_keuangan_kota_6  = 0;
      $target_btl_keuangan_kota_7  = 0;
      $target_btl_keuangan_kota_8  = 0;
      $target_btl_keuangan_kota_9  = 0;
      $target_btl_keuangan_kota_10 = 0;
      $target_btl_keuangan_kota_11 = 0;
      $target_btl_keuangan_kota_12 = 0; 

      $realisasi_bl_fisik_kota_1     = 0.0;
      $realisasi_bl_fisik_kota_2     = 0.0;
      $realisasi_bl_fisik_kota_3     = 0.0;
      $realisasi_bl_fisik_kota_4     = 0.0;
      $realisasi_bl_fisik_kota_5     = 0.0;
      $realisasi_bl_fisik_kota_6     = 0.0;
      $realisasi_bl_fisik_kota_7     = 0.0;
      $realisasi_bl_fisik_kota_8     = 0.0;
      $realisasi_bl_fisik_kota_9     = 0.0;
      $realisasi_bl_fisik_kota_10    = 0.0;
      $realisasi_bl_fisik_kota_11    = 0.0;
      $realisasi_bl_fisik_kota_12    = 0.0;
      $realisasi_bl_keuangan_kota_1  = 0;
      $realisasi_bl_keuangan_kota_2  = 0;
      $realisasi_bl_keuangan_kota_3  = 0;
      $realisasi_bl_keuangan_kota_4  = 0;
      $realisasi_bl_keuangan_kota_5  = 0;
      $realisasi_bl_keuangan_kota_6  = 0;
      $realisasi_bl_keuangan_kota_7  = 0;
      $realisasi_bl_keuangan_kota_8  = 0;
      $realisasi_bl_keuangan_kota_9  = 0;
      $realisasi_bl_keuangan_kota_10 = 0;
      $realisasi_bl_keuangan_kota_11 = 0;
      $realisasi_bl_keuangan_kota_12 = 0;

      $realisasi_btl_fisik_kota_1     = 0.0;
      $realisasi_btl_fisik_kota_2     = 0.0;
      $realisasi_btl_fisik_kota_3     = 0.0;
      $realisasi_btl_fisik_kota_4     = 0.0;
      $realisasi_btl_fisik_kota_5     = 0.0;
      $realisasi_btl_fisik_kota_6     = 0.0;
      $realisasi_btl_fisik_kota_7     = 0.0;
      $realisasi_btl_fisik_kota_8     = 0.0;
      $realisasi_btl_fisik_kota_9     = 0.0;
      $realisasi_btl_fisik_kota_10    = 0.0;
      $realisasi_btl_fisik_kota_11    = 0.0;
      $realisasi_btl_fisik_kota_12    = 0.0;
      $realisasi_btl_keuangan_kota_1  = 0;
      $realisasi_btl_keuangan_kota_2  = 0;
      $realisasi_btl_keuangan_kota_3  = 0;
      $realisasi_btl_keuangan_kota_4  = 0;
      $realisasi_btl_keuangan_kota_5  = 0;
      $realisasi_btl_keuangan_kota_6  = 0;
      $realisasi_btl_keuangan_kota_7  = 0;
      $realisasi_btl_keuangan_kota_8  = 0;
      $realisasi_btl_keuangan_kota_9  = 0;
      $realisasi_btl_keuangan_kota_10 = 0;
      $realisasi_btl_keuangan_kota_11 = 0;
      $realisasi_btl_keuangan_kota_12 = 0;      

      $i = 0;
      foreach ($tabel_pd as $pd) {
          // target
          $target_bl_fisik_kota_1     = $target_bl_fisik_kota_1     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_1"]);
          $target_bl_fisik_kota_2     = $target_bl_fisik_kota_2     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_2"]);
          $target_bl_fisik_kota_3     = $target_bl_fisik_kota_3     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_3"]);
          $target_bl_fisik_kota_4     = $target_bl_fisik_kota_4     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_4"]);
          $target_bl_fisik_kota_5     = $target_bl_fisik_kota_5     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_5"]);
          $target_bl_fisik_kota_6     = $target_bl_fisik_kota_6     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_6"]);
          $target_bl_fisik_kota_7     = $target_bl_fisik_kota_7     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_7"]);
          $target_bl_fisik_kota_8     = $target_bl_fisik_kota_8     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_8"]);
          $target_bl_fisik_kota_9     = $target_bl_fisik_kota_9     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_9"]);
          $target_bl_fisik_kota_10    = $target_bl_fisik_kota_10    + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_10"]);
          $target_bl_fisik_kota_11    = $target_bl_fisik_kota_11    + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_11"]);
          $target_bl_fisik_kota_12    = $target_bl_fisik_kota_12    + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["tf_12"]);
          $target_bl_keuangan_kota_1  = $target_bl_keuangan_kota_1  + $pd["tk_1"];
          $target_bl_keuangan_kota_2  = $target_bl_keuangan_kota_2  + $pd["tk_2"];
          $target_bl_keuangan_kota_3  = $target_bl_keuangan_kota_3  + $pd["tk_3"];
          $target_bl_keuangan_kota_4  = $target_bl_keuangan_kota_4  + $pd["tk_4"];
          $target_bl_keuangan_kota_5  = $target_bl_keuangan_kota_5  + $pd["tk_5"];
          $target_bl_keuangan_kota_6  = $target_bl_keuangan_kota_6  + $pd["tk_6"];
          $target_bl_keuangan_kota_7  = $target_bl_keuangan_kota_7  + $pd["tk_7"];
          $target_bl_keuangan_kota_8  = $target_bl_keuangan_kota_8  + $pd["tk_8"];
          $target_bl_keuangan_kota_9  = $target_bl_keuangan_kota_9  + $pd["tk_9"];
          $target_bl_keuangan_kota_10 = $target_bl_keuangan_kota_10 + $pd["tk_10"];
          $target_bl_keuangan_kota_11 = $target_bl_keuangan_kota_11 + $pd["tk_11"];
          $target_bl_keuangan_kota_12 = $target_bl_keuangan_kota_12 + $pd["tk_12"];
          $target_btl_fisik_kota_1     = $target_btl_fisik_kota_1     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_1"]);
          $target_btl_fisik_kota_2     = $target_btl_fisik_kota_2     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_2"]);
          $target_btl_fisik_kota_3     = $target_btl_fisik_kota_3     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_3"]);
          $target_btl_fisik_kota_4     = $target_btl_fisik_kota_4     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_4"]);
          $target_btl_fisik_kota_5     = $target_btl_fisik_kota_5     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_5"]);
          $target_btl_fisik_kota_6     = $target_btl_fisik_kota_6     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_6"]);
          $target_btl_fisik_kota_7     = $target_btl_fisik_kota_7     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_7"]);
          $target_btl_fisik_kota_8     = $target_btl_fisik_kota_8     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_8"]);
          $target_btl_fisik_kota_9     = $target_btl_fisik_kota_9     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_9"]);
          $target_btl_fisik_kota_10    = $target_btl_fisik_kota_10    + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_10"]);
          $target_btl_fisik_kota_11    = $target_btl_fisik_kota_11    + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_11"]);
          $target_btl_fisik_kota_12    = $target_btl_fisik_kota_12    + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_tf_12"]);
          $target_btl_keuangan_kota_1  = $target_btl_keuangan_kota_1  + $pd["btl_tk_1"];
          $target_btl_keuangan_kota_2  = $target_btl_keuangan_kota_2  + $pd["btl_tk_2"];
          $target_btl_keuangan_kota_3  = $target_btl_keuangan_kota_3  + $pd["btl_tk_3"];
          $target_btl_keuangan_kota_4  = $target_btl_keuangan_kota_4  + $pd["btl_tk_4"];
          $target_btl_keuangan_kota_5  = $target_btl_keuangan_kota_5  + $pd["btl_tk_5"];
          $target_btl_keuangan_kota_6  = $target_btl_keuangan_kota_6  + $pd["btl_tk_6"];
          $target_btl_keuangan_kota_7  = $target_btl_keuangan_kota_7  + $pd["btl_tk_7"];
          $target_btl_keuangan_kota_8  = $target_btl_keuangan_kota_8  + $pd["btl_tk_8"];
          $target_btl_keuangan_kota_9  = $target_btl_keuangan_kota_9  + $pd["btl_tk_9"];
          $target_btl_keuangan_kota_10 = $target_btl_keuangan_kota_10 + $pd["btl_tk_10"];
          $target_btl_keuangan_kota_11 = $target_btl_keuangan_kota_11 + $pd["btl_tk_11"];
          $target_btl_keuangan_kota_12 = $target_btl_keuangan_kota_12 + $pd["btl_tk_12"];
          // realisasi            
          $realisasi_bl_fisik_kota_1     = $realisasi_bl_fisik_kota_1     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_1"]);
          $realisasi_bl_fisik_kota_2     = $realisasi_bl_fisik_kota_2     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_2"]);
          $realisasi_bl_fisik_kota_3     = $realisasi_bl_fisik_kota_3     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_3"]);
          $realisasi_bl_fisik_kota_4     = $realisasi_bl_fisik_kota_4     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_4"]);
          $realisasi_bl_fisik_kota_5     = $realisasi_bl_fisik_kota_5     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_5"]);
          $realisasi_bl_fisik_kota_6     = $realisasi_bl_fisik_kota_6     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_6"]);
          $realisasi_bl_fisik_kota_7     = $realisasi_bl_fisik_kota_7     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_7"]);
          $realisasi_bl_fisik_kota_8     = $realisasi_bl_fisik_kota_8     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_8"]);
          $realisasi_bl_fisik_kota_9     = $realisasi_bl_fisik_kota_9     + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_9"]);
          $realisasi_bl_fisik_kota_10    = $realisasi_bl_fisik_kota_10    + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_10"]);
          $realisasi_bl_fisik_kota_11    = $realisasi_bl_fisik_kota_11    + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_11"]);
          $realisasi_bl_fisik_kota_12    = $realisasi_bl_fisik_kota_12    + (($pd["anggaran_total"] / $tabel_kota["anggaran_bl"]) * $pd["kf_12"]);
          $realisasi_bl_keuangan_kota_1  = $realisasi_bl_keuangan_kota_1  + $pd["kk_1"];
          $realisasi_bl_keuangan_kota_2  = $realisasi_bl_keuangan_kota_2  + $pd["kk_2"];
          $realisasi_bl_keuangan_kota_3  = $realisasi_bl_keuangan_kota_3  + $pd["kk_3"];
          $realisasi_bl_keuangan_kota_4  = $realisasi_bl_keuangan_kota_4  + $pd["kk_4"];
          $realisasi_bl_keuangan_kota_5  = $realisasi_bl_keuangan_kota_5  + $pd["kk_5"];
          $realisasi_bl_keuangan_kota_6  = $realisasi_bl_keuangan_kota_6  + $pd["kk_6"];
          $realisasi_bl_keuangan_kota_7  = $realisasi_bl_keuangan_kota_7  + $pd["kk_7"];
          $realisasi_bl_keuangan_kota_8  = $realisasi_bl_keuangan_kota_8  + $pd["kk_8"];
          $realisasi_bl_keuangan_kota_9  = $realisasi_bl_keuangan_kota_9  + $pd["kk_9"];
          $realisasi_bl_keuangan_kota_10 = $realisasi_bl_keuangan_kota_10 + $pd["kk_10"];
          $realisasi_bl_keuangan_kota_11 = $realisasi_bl_keuangan_kota_11 + $pd["kk_11"];
          $realisasi_bl_keuangan_kota_12 = $realisasi_bl_keuangan_kota_12 + $pd["kk_12"];
          $realisasi_btl_fisik_kota_1     = $realisasi_btl_fisik_kota_1     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_1"]);
          $realisasi_btl_fisik_kota_2     = $realisasi_btl_fisik_kota_2     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_2"]);
          $realisasi_btl_fisik_kota_3     = $realisasi_btl_fisik_kota_3     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_3"]);
          $realisasi_btl_fisik_kota_4     = $realisasi_btl_fisik_kota_4     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_4"]);
          $realisasi_btl_fisik_kota_5     = $realisasi_btl_fisik_kota_5     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_5"]);
          $realisasi_btl_fisik_kota_6     = $realisasi_btl_fisik_kota_6     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_6"]);
          $realisasi_btl_fisik_kota_7     = $realisasi_btl_fisik_kota_7     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_7"]);
          $realisasi_btl_fisik_kota_8     = $realisasi_btl_fisik_kota_8     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_8"]);
          $realisasi_btl_fisik_kota_9     = $realisasi_btl_fisik_kota_9     + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_9"]);
          $realisasi_btl_fisik_kota_10    = $realisasi_btl_fisik_kota_10    + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_10"]);
          $realisasi_btl_fisik_kota_11    = $realisasi_btl_fisik_kota_11    + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_11"]);
          $realisasi_btl_fisik_kota_12    = $realisasi_btl_fisik_kota_12    + (($pd["anggaran_total"] / $tabel_kota["anggaran_btl"]) * $pd["btl_rf_12"]);
          $realisasi_btl_keuangan_kota_1  = $realisasi_btl_keuangan_kota_1  + $pd["btl_rk_1"];
          $realisasi_btl_keuangan_kota_2  = $realisasi_btl_keuangan_kota_2  + $pd["btl_rk_2"];
          $realisasi_btl_keuangan_kota_3  = $realisasi_btl_keuangan_kota_3  + $pd["btl_rk_3"];
          $realisasi_btl_keuangan_kota_4  = $realisasi_btl_keuangan_kota_4  + $pd["btl_rk_4"];
          $realisasi_btl_keuangan_kota_5  = $realisasi_btl_keuangan_kota_5  + $pd["btl_rk_5"];
          $realisasi_btl_keuangan_kota_6  = $realisasi_btl_keuangan_kota_6  + $pd["btl_rk_6"];
          $realisasi_btl_keuangan_kota_7  = $realisasi_btl_keuangan_kota_7  + $pd["btl_rk_7"];
          $realisasi_btl_keuangan_kota_8  = $realisasi_btl_keuangan_kota_8  + $pd["btl_rk_8"];
          $realisasi_btl_keuangan_kota_9  = $realisasi_btl_keuangan_kota_9  + $pd["btl_rk_9"];
          $realisasi_btl_keuangan_kota_10 = $realisasi_btl_keuangan_kota_10 + $pd["btl_rk_10"];
          $realisasi_btl_keuangan_kota_11 = $realisasi_btl_keuangan_kota_11 + $pd["btl_rk_11"];
          $realisasi_btl_keuangan_kota_12 = $realisasi_btl_keuangan_kota_12 + $pd["btl_rk_12"];

      }  

      // Buat array Tabel Kota

      // target
      $tabel_kota["target_bl_fisik_kota_1"     ] = $target_bl_fisik_kota_1     ;
      $tabel_kota["target_bl_fisik_kota_2"     ] = $target_bl_fisik_kota_2     ;
      $tabel_kota["target_bl_fisik_kota_3"     ] = $target_bl_fisik_kota_3     ;
      $tabel_kota["target_bl_fisik_kota_4"     ] = $target_bl_fisik_kota_4     ;
      $tabel_kota["target_bl_fisik_kota_5"     ] = $target_bl_fisik_kota_5     ;
      $tabel_kota["target_bl_fisik_kota_6"     ] = $target_bl_fisik_kota_6     ;
      $tabel_kota["target_bl_fisik_kota_7"     ] = $target_bl_fisik_kota_7     ;
      $tabel_kota["target_bl_fisik_kota_8"     ] = $target_bl_fisik_kota_8     ;
      $tabel_kota["target_bl_fisik_kota_9"     ] = $target_bl_fisik_kota_9     ;
      $tabel_kota["target_bl_fisik_kota_10"    ] = $target_bl_fisik_kota_10    ;
      $tabel_kota["target_bl_fisik_kota_11"    ] = $target_bl_fisik_kota_11    ;
      $tabel_kota["target_bl_fisik_kota_12"    ] = $target_bl_fisik_kota_12    ;
      $tabel_kota["target_bl_keuangan_kota_1"  ] = $target_bl_keuangan_kota_1  ;
      $tabel_kota["target_bl_keuangan_kota_2"  ] = $target_bl_keuangan_kota_2  ;
      $tabel_kota["target_bl_keuangan_kota_3"  ] = $target_bl_keuangan_kota_3  ;
      $tabel_kota["target_bl_keuangan_kota_4"  ] = $target_bl_keuangan_kota_4  ;
      $tabel_kota["target_bl_keuangan_kota_5"  ] = $target_bl_keuangan_kota_5  ;
      $tabel_kota["target_bl_keuangan_kota_6"  ] = $target_bl_keuangan_kota_6  ;
      $tabel_kota["target_bl_keuangan_kota_7"  ] = $target_bl_keuangan_kota_7  ;
      $tabel_kota["target_bl_keuangan_kota_8"  ] = $target_bl_keuangan_kota_8  ;
      $tabel_kota["target_bl_keuangan_kota_9"  ] = $target_bl_keuangan_kota_9  ;
      $tabel_kota["target_bl_keuangan_kota_10" ] = $target_bl_keuangan_kota_10 ;
      $tabel_kota["target_bl_keuangan_kota_11" ] = $target_bl_keuangan_kota_11 ;
      $tabel_kota["target_bl_keuangan_kota_12" ] = $target_bl_keuangan_kota_12 ;
      $tabel_kota["target_bl_keuangan_kota_persen_1"  ] = ($target_bl_keuangan_kota_1  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_2"  ] = ($target_bl_keuangan_kota_2  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_3"  ] = ($target_bl_keuangan_kota_3  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_4"  ] = ($target_bl_keuangan_kota_4  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_5"  ] = ($target_bl_keuangan_kota_5  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_6"  ] = ($target_bl_keuangan_kota_6  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_7"  ] = ($target_bl_keuangan_kota_7  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_8"  ] = ($target_bl_keuangan_kota_8  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_9"  ] = ($target_bl_keuangan_kota_9  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_10" ] = ($target_bl_keuangan_kota_10 / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_11" ] = ($target_bl_keuangan_kota_11 / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_bl_keuangan_kota_persen_12" ] = ($target_bl_keuangan_kota_12 / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["target_btl_fisik_kota_1"    ] = $target_btl_fisik_kota_1    ;
      $tabel_kota["target_btl_fisik_kota_2"    ] = $target_btl_fisik_kota_2    ;
      $tabel_kota["target_btl_fisik_kota_3"    ] = $target_btl_fisik_kota_3    ;
      $tabel_kota["target_btl_fisik_kota_4"    ] = $target_btl_fisik_kota_4    ;
      $tabel_kota["target_btl_fisik_kota_5"    ] = $target_btl_fisik_kota_5    ;
      $tabel_kota["target_btl_fisik_kota_6"    ] = $target_btl_fisik_kota_6    ;
      $tabel_kota["target_btl_fisik_kota_7"    ] = $target_btl_fisik_kota_7    ;
      $tabel_kota["target_btl_fisik_kota_8"    ] = $target_btl_fisik_kota_8    ;
      $tabel_kota["target_btl_fisik_kota_9"    ] = $target_btl_fisik_kota_9    ;
      $tabel_kota["target_btl_fisik_kota_10"   ] = $target_btl_fisik_kota_10   ;
      $tabel_kota["target_btl_fisik_kota_11"   ] = $target_btl_fisik_kota_11   ;
      $tabel_kota["target_btl_fisik_kota_12"   ] = $target_btl_fisik_kota_12   ;
      $tabel_kota["target_btl_keuangan_kota_1" ] = $target_btl_keuangan_kota_1 ;
      $tabel_kota["target_btl_keuangan_kota_2" ] = $target_btl_keuangan_kota_2 ;
      $tabel_kota["target_btl_keuangan_kota_3" ] = $target_btl_keuangan_kota_3 ;
      $tabel_kota["target_btl_keuangan_kota_4" ] = $target_btl_keuangan_kota_4 ;
      $tabel_kota["target_btl_keuangan_kota_5" ] = $target_btl_keuangan_kota_5 ;
      $tabel_kota["target_btl_keuangan_kota_6" ] = $target_btl_keuangan_kota_6 ;
      $tabel_kota["target_btl_keuangan_kota_7" ] = $target_btl_keuangan_kota_7 ;
      $tabel_kota["target_btl_keuangan_kota_8" ] = $target_btl_keuangan_kota_8 ;
      $tabel_kota["target_btl_keuangan_kota_9" ] = $target_btl_keuangan_kota_9 ;
      $tabel_kota["target_btl_keuangan_kota_10"] = $target_btl_keuangan_kota_10;
      $tabel_kota["target_btl_keuangan_kota_11"] = $target_btl_keuangan_kota_11;
      $tabel_kota["target_btl_keuangan_kota_12"] = $target_btl_keuangan_kota_12;
      $tabel_kota["target_btl_keuangan_kota_persen_1"  ] = ($target_btl_keuangan_kota_1  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_2"  ] = ($target_btl_keuangan_kota_2  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_3"  ] = ($target_btl_keuangan_kota_3  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_4"  ] = ($target_btl_keuangan_kota_4  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_5"  ] = ($target_btl_keuangan_kota_5  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_6"  ] = ($target_btl_keuangan_kota_6  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_7"  ] = ($target_btl_keuangan_kota_7  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_8"  ] = ($target_btl_keuangan_kota_8  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_9"  ] = ($target_btl_keuangan_kota_9  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_10" ] = ($target_btl_keuangan_kota_10 / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_11" ] = ($target_btl_keuangan_kota_11 / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["target_btl_keuangan_kota_persen_12" ] = ($target_btl_keuangan_kota_12 / $tabel_kota["anggaran_btl"]) * 100;      
      // realisasi
      $tabel_kota["realisasi_bl_fisik_kota_1"     ] = $realisasi_bl_fisik_kota_1     ;
      $tabel_kota["realisasi_bl_fisik_kota_2"     ] = $realisasi_bl_fisik_kota_2     ;
      $tabel_kota["realisasi_bl_fisik_kota_3"     ] = $realisasi_bl_fisik_kota_3     ;
      $tabel_kota["realisasi_bl_fisik_kota_4"     ] = $realisasi_bl_fisik_kota_4     ;
      $tabel_kota["realisasi_bl_fisik_kota_5"     ] = $realisasi_bl_fisik_kota_5     ;
      $tabel_kota["realisasi_bl_fisik_kota_6"     ] = $realisasi_bl_fisik_kota_6     ;
      $tabel_kota["realisasi_bl_fisik_kota_7"     ] = $realisasi_bl_fisik_kota_7     ;
      $tabel_kota["realisasi_bl_fisik_kota_8"     ] = $realisasi_bl_fisik_kota_8     ;
      $tabel_kota["realisasi_bl_fisik_kota_9"     ] = $realisasi_bl_fisik_kota_9     ;
      $tabel_kota["realisasi_bl_fisik_kota_10"    ] = $realisasi_bl_fisik_kota_10    ;
      $tabel_kota["realisasi_bl_fisik_kota_11"    ] = $realisasi_bl_fisik_kota_11    ;
      $tabel_kota["realisasi_bl_fisik_kota_12"    ] = $realisasi_bl_fisik_kota_12    ;
      $tabel_kota["realisasi_bl_keuangan_kota_1"  ] = $realisasi_bl_keuangan_kota_1  ;
      $tabel_kota["realisasi_bl_keuangan_kota_2"  ] = $realisasi_bl_keuangan_kota_2  ;
      $tabel_kota["realisasi_bl_keuangan_kota_3"  ] = $realisasi_bl_keuangan_kota_3  ;
      $tabel_kota["realisasi_bl_keuangan_kota_4"  ] = $realisasi_bl_keuangan_kota_4  ;
      $tabel_kota["realisasi_bl_keuangan_kota_5"  ] = $realisasi_bl_keuangan_kota_5  ;
      $tabel_kota["realisasi_bl_keuangan_kota_6"  ] = $realisasi_bl_keuangan_kota_6  ;
      $tabel_kota["realisasi_bl_keuangan_kota_7"  ] = $realisasi_bl_keuangan_kota_7  ;
      $tabel_kota["realisasi_bl_keuangan_kota_8"  ] = $realisasi_bl_keuangan_kota_8  ;
      $tabel_kota["realisasi_bl_keuangan_kota_9"  ] = $realisasi_bl_keuangan_kota_9  ;
      $tabel_kota["realisasi_bl_keuangan_kota_10" ] = $realisasi_bl_keuangan_kota_10 ;
      $tabel_kota["realisasi_bl_keuangan_kota_11" ] = $realisasi_bl_keuangan_kota_11 ;
      $tabel_kota["realisasi_bl_keuangan_kota_12" ] = $realisasi_bl_keuangan_kota_12 ;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_1"  ] = ($realisasi_bl_keuangan_kota_1  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_2"  ] = ($realisasi_bl_keuangan_kota_2  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_3"  ] = ($realisasi_bl_keuangan_kota_3  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_4"  ] = ($realisasi_bl_keuangan_kota_4  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_5"  ] = ($realisasi_bl_keuangan_kota_5  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_6"  ] = ($realisasi_bl_keuangan_kota_6  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_7"  ] = ($realisasi_bl_keuangan_kota_7  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_8"  ] = ($realisasi_bl_keuangan_kota_8  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_9"  ] = ($realisasi_bl_keuangan_kota_9  / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_10" ] = ($realisasi_bl_keuangan_kota_10 / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_11" ] = ($realisasi_bl_keuangan_kota_11 / $tabel_kota["anggaran_bl"]) * 100;
      $tabel_kota["realisasi_bl_keuangan_kota_persen_12" ] = ($realisasi_bl_keuangan_kota_12 / $tabel_kota["anggaran_bl"]) * 100;      
      $tabel_kota["realisasi_btl_fisik_kota_1"    ] = $realisasi_btl_fisik_kota_1    ;
      $tabel_kota["realisasi_btl_fisik_kota_2"    ] = $realisasi_btl_fisik_kota_2    ;
      $tabel_kota["realisasi_btl_fisik_kota_3"    ] = $realisasi_btl_fisik_kota_3    ;
      $tabel_kota["realisasi_btl_fisik_kota_4"    ] = $realisasi_btl_fisik_kota_4    ;
      $tabel_kota["realisasi_btl_fisik_kota_5"    ] = $realisasi_btl_fisik_kota_5    ;
      $tabel_kota["realisasi_btl_fisik_kota_6"    ] = $realisasi_btl_fisik_kota_6    ;
      $tabel_kota["realisasi_btl_fisik_kota_7"    ] = $realisasi_btl_fisik_kota_7    ;
      $tabel_kota["realisasi_btl_fisik_kota_8"    ] = $realisasi_btl_fisik_kota_8    ;
      $tabel_kota["realisasi_btl_fisik_kota_9"    ] = $realisasi_btl_fisik_kota_9    ;
      $tabel_kota["realisasi_btl_fisik_kota_10"   ] = $realisasi_btl_fisik_kota_10   ;
      $tabel_kota["realisasi_btl_fisik_kota_11"   ] = $realisasi_btl_fisik_kota_11   ;
      $tabel_kota["realisasi_btl_fisik_kota_12"   ] = $realisasi_btl_fisik_kota_12   ;
      $tabel_kota["realisasi_btl_keuangan_kota_1" ] = $realisasi_btl_keuangan_kota_1 ;
      $tabel_kota["realisasi_btl_keuangan_kota_2" ] = $realisasi_btl_keuangan_kota_2 ;
      $tabel_kota["realisasi_btl_keuangan_kota_3" ] = $realisasi_btl_keuangan_kota_3 ;
      $tabel_kota["realisasi_btl_keuangan_kota_4" ] = $realisasi_btl_keuangan_kota_4 ;
      $tabel_kota["realisasi_btl_keuangan_kota_5" ] = $realisasi_btl_keuangan_kota_5 ;
      $tabel_kota["realisasi_btl_keuangan_kota_6" ] = $realisasi_btl_keuangan_kota_6 ;
      $tabel_kota["realisasi_btl_keuangan_kota_7" ] = $realisasi_btl_keuangan_kota_7 ;
      $tabel_kota["realisasi_btl_keuangan_kota_8" ] = $realisasi_btl_keuangan_kota_8 ;
      $tabel_kota["realisasi_btl_keuangan_kota_9" ] = $realisasi_btl_keuangan_kota_9 ;
      $tabel_kota["realisasi_btl_keuangan_kota_10"] = $realisasi_btl_keuangan_kota_10;
      $tabel_kota["realisasi_btl_keuangan_kota_11"] = $realisasi_btl_keuangan_kota_11;
      $tabel_kota["realisasi_btl_keuangan_kota_12"] = $realisasi_btl_keuangan_kota_12;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_1"  ] = ($realisasi_btl_keuangan_kota_1  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_2"  ] = ($realisasi_btl_keuangan_kota_2  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_3"  ] = ($realisasi_btl_keuangan_kota_3  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_4"  ] = ($realisasi_btl_keuangan_kota_4  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_5"  ] = ($realisasi_btl_keuangan_kota_5  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_6"  ] = ($realisasi_btl_keuangan_kota_6  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_7"  ] = ($realisasi_btl_keuangan_kota_7  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_8"  ] = ($realisasi_btl_keuangan_kota_8  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_9"  ] = ($realisasi_btl_keuangan_kota_9  / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_10" ] = ($realisasi_btl_keuangan_kota_10 / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_11" ] = ($realisasi_btl_keuangan_kota_11 / $tabel_kota["anggaran_btl"]) * 100;
      $tabel_kota["realisasi_btl_keuangan_kota_persen_12" ] = ($realisasi_btl_keuangan_kota_12 / $tabel_kota["anggaran_btl"]) * 100;       

      // total kota     

      // target fisik
      $bobot_bl_fisik = $tabel_kota["anggaran_bl"] / $tabel_kota["anggaran_total"];
      $bobot_btl_fisik = $tabel_kota["anggaran_btl"] / $tabel_kota["anggaran_total"];
      $tabel_kota["target_fisik_kota_1" ] = ($tabel_kota["target_bl_fisik_kota_1" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_1" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_2" ] = ($tabel_kota["target_bl_fisik_kota_2" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_2" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_3" ] = ($tabel_kota["target_bl_fisik_kota_3" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_3" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_4" ] = ($tabel_kota["target_bl_fisik_kota_4" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_4" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_5" ] = ($tabel_kota["target_bl_fisik_kota_5" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_5" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_6" ] = ($tabel_kota["target_bl_fisik_kota_6" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_6" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_7" ] = ($tabel_kota["target_bl_fisik_kota_7" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_7" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_8" ] = ($tabel_kota["target_bl_fisik_kota_8" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_8" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_9" ] = ($tabel_kota["target_bl_fisik_kota_9" ] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_9" ] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_10"] = ($tabel_kota["target_bl_fisik_kota_10"] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_10"] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_11"] = ($tabel_kota["target_bl_fisik_kota_11"] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_11"] * $bobot_btl_fisik);
      $tabel_kota["target_fisik_kota_12"] = ($tabel_kota["target_bl_fisik_kota_12"] * $bobot_bl_fisik) + ($tabel_kota["target_btl_fisik_kota_12"] * $bobot_btl_fisik);
      // target keuangan
      $tabel_kota["target_keuangan_kota_1" ] = $tabel_kota["target_bl_keuangan_kota_1" ] + $tabel_kota["target_btl_keuangan_kota_1" ];
      $tabel_kota["target_keuangan_kota_2" ] = $tabel_kota["target_bl_keuangan_kota_2" ] + $tabel_kota["target_btl_keuangan_kota_2" ];
      $tabel_kota["target_keuangan_kota_3" ] = $tabel_kota["target_bl_keuangan_kota_3" ] + $tabel_kota["target_btl_keuangan_kota_3" ];
      $tabel_kota["target_keuangan_kota_4" ] = $tabel_kota["target_bl_keuangan_kota_4" ] + $tabel_kota["target_btl_keuangan_kota_4" ];
      $tabel_kota["target_keuangan_kota_5" ] = $tabel_kota["target_bl_keuangan_kota_5" ] + $tabel_kota["target_btl_keuangan_kota_5" ];
      $tabel_kota["target_keuangan_kota_6" ] = $tabel_kota["target_bl_keuangan_kota_6" ] + $tabel_kota["target_btl_keuangan_kota_6" ];
      $tabel_kota["target_keuangan_kota_7" ] = $tabel_kota["target_bl_keuangan_kota_7" ] + $tabel_kota["target_btl_keuangan_kota_7" ];
      $tabel_kota["target_keuangan_kota_8" ] = $tabel_kota["target_bl_keuangan_kota_8" ] + $tabel_kota["target_btl_keuangan_kota_8" ];
      $tabel_kota["target_keuangan_kota_9" ] = $tabel_kota["target_bl_keuangan_kota_9" ] + $tabel_kota["target_btl_keuangan_kota_9" ];
      $tabel_kota["target_keuangan_kota_10"] = $tabel_kota["target_bl_keuangan_kota_10"] + $tabel_kota["target_btl_keuangan_kota_10"];
      $tabel_kota["target_keuangan_kota_11"] = $tabel_kota["target_bl_keuangan_kota_11"] + $tabel_kota["target_btl_keuangan_kota_11"];
      $tabel_kota["target_keuangan_kota_12"] = $tabel_kota["target_bl_keuangan_kota_12"] + $tabel_kota["target_btl_keuangan_kota_12"];
      // target keuangan persen
      $tabel_kota["target_keuangan_kota_persen_1" ] = ($tabel_kota["target_keuangan_kota_1" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_2" ] = ($tabel_kota["target_keuangan_kota_2" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_3" ] = ($tabel_kota["target_keuangan_kota_3" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_4" ] = ($tabel_kota["target_keuangan_kota_4" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_5" ] = ($tabel_kota["target_keuangan_kota_5" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_6" ] = ($tabel_kota["target_keuangan_kota_6" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_7" ] = ($tabel_kota["target_keuangan_kota_7" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_8" ] = ($tabel_kota["target_keuangan_kota_8" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_9" ] = ($tabel_kota["target_keuangan_kota_9" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_10"] = ($tabel_kota["target_keuangan_kota_10"] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_11"] = ($tabel_kota["target_keuangan_kota_11"] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["target_keuangan_kota_persen_12"] = ($tabel_kota["target_keuangan_kota_12"] / $tabel_kota["anggaran_total"] ) * 100;
      // realisasi fisik
      $tabel_kota["realisasi_fisik_kota_1" ] = ($tabel_kota["realisasi_bl_fisik_kota_1" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_1" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_2" ] = ($tabel_kota["realisasi_bl_fisik_kota_2" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_2" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_3" ] = ($tabel_kota["realisasi_bl_fisik_kota_3" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_3" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_4" ] = ($tabel_kota["realisasi_bl_fisik_kota_4" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_4" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_5" ] = ($tabel_kota["realisasi_bl_fisik_kota_5" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_5" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_6" ] = ($tabel_kota["realisasi_bl_fisik_kota_6" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_6" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_7" ] = ($tabel_kota["realisasi_bl_fisik_kota_7" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_7" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_8" ] = ($tabel_kota["realisasi_bl_fisik_kota_8" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_8" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_9" ] = ($tabel_kota["realisasi_bl_fisik_kota_9" ] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_9" ] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_10"] = ($tabel_kota["realisasi_bl_fisik_kota_10"] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_10"] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_11"] = ($tabel_kota["realisasi_bl_fisik_kota_11"] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_11"] * $bobot_btl_fisik);
      $tabel_kota["realisasi_fisik_kota_12"] = ($tabel_kota["realisasi_bl_fisik_kota_12"] * $bobot_bl_fisik) + ($tabel_kota["realisasi_btl_fisik_kota_12"] * $bobot_btl_fisik);
      // realisasi keuangan
      $tabel_kota["realisasi_keuangan_kota_1" ] = $tabel_kota["realisasi_bl_keuangan_kota_1" ] + $tabel_kota["realisasi_btl_keuangan_kota_1" ];
      $tabel_kota["realisasi_keuangan_kota_2" ] = $tabel_kota["realisasi_bl_keuangan_kota_2" ] + $tabel_kota["realisasi_btl_keuangan_kota_2" ];
      $tabel_kota["realisasi_keuangan_kota_3" ] = $tabel_kota["realisasi_bl_keuangan_kota_3" ] + $tabel_kota["realisasi_btl_keuangan_kota_3" ];
      $tabel_kota["realisasi_keuangan_kota_4" ] = $tabel_kota["realisasi_bl_keuangan_kota_4" ] + $tabel_kota["realisasi_btl_keuangan_kota_4" ];
      $tabel_kota["realisasi_keuangan_kota_5" ] = $tabel_kota["realisasi_bl_keuangan_kota_5" ] + $tabel_kota["realisasi_btl_keuangan_kota_5" ];
      $tabel_kota["realisasi_keuangan_kota_6" ] = $tabel_kota["realisasi_bl_keuangan_kota_6" ] + $tabel_kota["realisasi_btl_keuangan_kota_6" ];
      $tabel_kota["realisasi_keuangan_kota_7" ] = $tabel_kota["realisasi_bl_keuangan_kota_7" ] + $tabel_kota["realisasi_btl_keuangan_kota_7" ];
      $tabel_kota["realisasi_keuangan_kota_8" ] = $tabel_kota["realisasi_bl_keuangan_kota_8" ] + $tabel_kota["realisasi_btl_keuangan_kota_8" ];
      $tabel_kota["realisasi_keuangan_kota_9" ] = $tabel_kota["realisasi_bl_keuangan_kota_9" ] + $tabel_kota["realisasi_btl_keuangan_kota_9" ];
      $tabel_kota["realisasi_keuangan_kota_10"] = $tabel_kota["realisasi_bl_keuangan_kota_10"] + $tabel_kota["realisasi_btl_keuangan_kota_10"];
      $tabel_kota["realisasi_keuangan_kota_11"] = $tabel_kota["realisasi_bl_keuangan_kota_11"] + $tabel_kota["realisasi_btl_keuangan_kota_11"];
      $tabel_kota["realisasi_keuangan_kota_12"] = $tabel_kota["realisasi_bl_keuangan_kota_12"] + $tabel_kota["realisasi_btl_keuangan_kota_12"];
      // realisasi keuangan persen
      $tabel_kota["realisasi_keuangan_kota_persen_1" ] = ($tabel_kota["realisasi_keuangan_kota_1" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_2" ] = ($tabel_kota["realisasi_keuangan_kota_2" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_3" ] = ($tabel_kota["realisasi_keuangan_kota_3" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_4" ] = ($tabel_kota["realisasi_keuangan_kota_4" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_5" ] = ($tabel_kota["realisasi_keuangan_kota_5" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_6" ] = ($tabel_kota["realisasi_keuangan_kota_6" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_7" ] = ($tabel_kota["realisasi_keuangan_kota_7" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_8" ] = ($tabel_kota["realisasi_keuangan_kota_8" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_9" ] = ($tabel_kota["realisasi_keuangan_kota_9" ] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_10"] = ($tabel_kota["realisasi_keuangan_kota_10"] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_11"] = ($tabel_kota["realisasi_keuangan_kota_11"] / $tabel_kota["anggaran_total"] ) * 100;
      $tabel_kota["realisasi_keuangan_kota_persen_12"] = ($tabel_kota["realisasi_keuangan_kota_12"] / $tabel_kota["anggaran_total"] ) * 100;



      return $tabel_kota;
    }


    function get_realisasi_bulanan_bl($pagu_total,$tahun_anggaran)
    {
      $sql = '
        SELECT
          # realisasi fisik PD
          SUM(a.kf_1 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_1,
          SUM(a.kf_2 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_2,
          SUM(a.kf_3 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_3,
          SUM(a.kf_4 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_4,
          SUM(a.kf_5 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_5,
          SUM(a.kf_6 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_6,
          SUM(a.kf_7 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_7,
          SUM(a.kf_8 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_8,
          SUM(a.kf_9 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_9,
          SUM(a.kf_10 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_10,
          SUM(a.kf_11 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_11,
          SUM(a.kf_12 * ROUND(a.pagu_giat / '.$pagu_total.',8)) AS realisasi_fisik_12,
          # realisasi keuangan kota
          ROUND(SUM(a.kk_1 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_1 ,
          ROUND(SUM(a.kk_2 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_2 ,
          ROUND(SUM(a.kk_3 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_3 ,
          ROUND(SUM(a.kk_4 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_4 ,
          ROUND(SUM(a.kk_5 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_5 ,
          ROUND(SUM(a.kk_6 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_6 ,
          ROUND(SUM(a.kk_7 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_7 ,
          ROUND(SUM(a.kk_8 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_8 ,
          ROUND(SUM(a.kk_9 ) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_9 ,
          ROUND(SUM(a.kk_10) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_10,
          ROUND(SUM(a.kk_11) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_11,
          ROUND(SUM(a.kk_12) / SUM(a.pagu_giat),8) * 100 AS realisasi_keuangan_12,
          # target fisik kota
          d.tf_1  AS target_fisik_1 ,
          d.tf_2  AS target_fisik_2 ,
          d.tf_3  AS target_fisik_3 ,
          d.tf_4  AS target_fisik_4 ,
          d.tf_5  AS target_fisik_5 ,
          d.tf_6  AS target_fisik_6 ,
          d.tf_7  AS target_fisik_7 ,
          d.tf_8  AS target_fisik_8 ,
          d.tf_9  AS target_fisik_9 ,
          d.tf_10 AS target_fisik_10,
          d.tf_11 AS target_fisik_11,
          d.tf_12 AS target_fisik_12,
          # target keuangan kota
          ROUND(d.tk_1 / '.$pagu_total.',8)*100  AS target_keuangan_1 ,
          ROUND(d.tk_2 / '.$pagu_total.',8)*100  AS target_keuangan_2 ,
          ROUND(d.tk_3 / '.$pagu_total.',8)*100  AS target_keuangan_3 ,
          ROUND(d.tk_4 / '.$pagu_total.',8)*100  AS target_keuangan_4 ,
          ROUND(d.tk_5 / '.$pagu_total.',8)*100  AS target_keuangan_5 ,
          ROUND(d.tk_6 / '.$pagu_total.',8)*100  AS target_keuangan_6 ,
          ROUND(d.tk_7 / '.$pagu_total.',8)*100  AS target_keuangan_7 ,
          ROUND(d.tk_8 / '.$pagu_total.',8)*100  AS target_keuangan_8 ,
          ROUND(d.tk_9 / '.$pagu_total.',8)*100  AS target_keuangan_9 ,
          ROUND(d.tk_10/ '.$pagu_total.',8)*100  AS target_keuangan_10,
          ROUND(d.tk_11/ '.$pagu_total.',8)*100  AS target_keuangan_11,
          ROUND(d.tk_12/ '.$pagu_total.',8)*100  AS target_keuangan_12
        FROM belanja AS a
        JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
        JOIN program AS c ON b.kode_prog = c.kode_prog
        JOIN pd AS d ON c.kode_pd = d.kode_pd
        WHERE 
          a.tahun_anggaran = "'.$tahun_anggaran.'" AND
          b.tahun_anggaran = "'.$tahun_anggaran.'" AND
          c.tahun_anggaran = "'.$tahun_anggaran.'" AND
          a.kode_giat NOT IN (SELECT kode_giat_btl FROM pd WHERE kode_giat_btl <> "")';
      $query = $this->db->query($sql);
      return $query->result()[0];      
    }

    function get_realisasi_bulanan_btl($pagu_total,$tahun_anggaran)
    {
      $sql = '
        SELECT
          # target fisik
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_1) AS target_fisik_1,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_2) AS target_fisik_2,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_3) AS target_fisik_3,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_4) AS target_fisik_4,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_5) AS target_fisik_5,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_6) AS target_fisik_6,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_7) AS target_fisik_7,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_8) AS target_fisik_8,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_9) AS target_fisik_9,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_10) AS target_fisik_10,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_11) AS target_fisik_11,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_tf_12) AS target_fisik_12,
          # realisasi fisik
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_1) AS realisasi_fisik_1,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_2) AS realisasi_fisik_2,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_3) AS realisasi_fisik_3,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_4) AS realisasi_fisik_4,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_5) AS realisasi_fisik_5,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_6) AS realisasi_fisik_6,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_7) AS realisasi_fisik_7,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_8) AS realisasi_fisik_8,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_9) AS realisasi_fisik_9,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_10) AS realisasi_fisik_10,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_11) AS realisasi_fisik_11,
          SUM(ROUND(anggaran_btl / '.$pagu_total.',8) * btl_rf_12) AS realisasi_fisik_12,
          # target keuangan
          ROUND(SUM(btl_tk_1 ) / '.$pagu_total.',8) * 100 AS target_keuangan_1 ,
          ROUND(SUM(btl_tk_2 ) / '.$pagu_total.',8) * 100 AS target_keuangan_2 ,
          ROUND(SUM(btl_tk_3 ) / '.$pagu_total.',8) * 100 AS target_keuangan_3 ,
          ROUND(SUM(btl_tk_4 ) / '.$pagu_total.',8) * 100 AS target_keuangan_4 ,
          ROUND(SUM(btl_tk_5 ) / '.$pagu_total.',8) * 100 AS target_keuangan_5 ,
          ROUND(SUM(btl_tk_6 ) / '.$pagu_total.',8) * 100 AS target_keuangan_6 ,
          ROUND(SUM(btl_tk_7 ) / '.$pagu_total.',8) * 100 AS target_keuangan_7 ,
          ROUND(SUM(btl_tk_8 ) / '.$pagu_total.',8) * 100 AS target_keuangan_8 ,
          ROUND(SUM(btl_tk_9 ) / '.$pagu_total.',8) * 100 AS target_keuangan_9 ,
          ROUND(SUM(btl_tk_10) / '.$pagu_total.',8) * 100 AS target_keuangan_10,
          ROUND(SUM(btl_tk_11) / '.$pagu_total.',8) * 100 AS target_keuangan_11,
          ROUND(SUM(btl_tk_12) / '.$pagu_total.',8) * 100 AS target_keuangan_12,
            # realisasi keuangan
          ROUND(SUM(btl_rk_1 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_1 ,
          ROUND(SUM(btl_rk_2 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_2 ,
          ROUND(SUM(btl_rk_3 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_3 ,
          ROUND(SUM(btl_rk_4 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_4 ,
          ROUND(SUM(btl_rk_5 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_5 ,
          ROUND(SUM(btl_rk_6 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_6 ,
          ROUND(SUM(btl_rk_7 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_7 ,
          ROUND(SUM(btl_rk_8 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_8 ,
          ROUND(SUM(btl_rk_9 ) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_9 ,
          ROUND(SUM(btl_rk_10) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_10,
          ROUND(SUM(btl_rk_11) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_11,
          ROUND(SUM(btl_rk_12) / '.$pagu_total.',8) * 100 AS realisasi_keuangan_12,
            # target keuangan rupiah
          SUM(btl_tk_1 ) AS target_keuangan_rp_1 ,
          SUM(btl_tk_2 ) AS target_keuangan_rp_2 ,
          SUM(btl_tk_3 ) AS target_keuangan_rp_3 ,
          SUM(btl_tk_4 ) AS target_keuangan_rp_4 ,
          SUM(btl_tk_5 ) AS target_keuangan_rp_5 ,
          SUM(btl_tk_6 ) AS target_keuangan_rp_6 ,
          SUM(btl_tk_7 ) AS target_keuangan_rp_7 ,
          SUM(btl_tk_8 ) AS target_keuangan_rp_8 ,
          SUM(btl_tk_9 ) AS target_keuangan_rp_9 ,
          SUM(btl_tk_10) AS target_keuangan_rp_10,
          SUM(btl_tk_11) AS target_keuangan_rp_11,
          SUM(btl_tk_12) AS target_keuangan_rp_12,
          # target keuangan rupiah
          SUM(btl_rk_1 ) AS realisasi_keuangan_rp_1 ,
          SUM(btl_rk_2 ) AS realisasi_keuangan_rp_2 ,
          SUM(btl_rk_3 ) AS realisasi_keuangan_rp_3 ,
          SUM(btl_rk_4 ) AS realisasi_keuangan_rp_4 ,
          SUM(btl_rk_5 ) AS realisasi_keuangan_rp_5 ,
          SUM(btl_rk_6 ) AS realisasi_keuangan_rp_6 ,
          SUM(btl_rk_7 ) AS realisasi_keuangan_rp_7 ,
          SUM(btl_rk_8 ) AS realisasi_keuangan_rp_8 ,
          SUM(btl_rk_9 ) AS realisasi_keuangan_rp_9 ,
          SUM(btl_rk_10) AS realisasi_keuangan_rp_10,
          SUM(btl_rk_11) AS realisasi_keuangan_rp_11,
          SUM(btl_rk_12) AS realisasi_keuangan_rp_12
        FROM daftar_pd_btl';
      $query = $this->db->query($sql);
      return $query->result()[0]; 
    }


    function get_kinerja_pptk($bulan_pelaporan)
    {
      $sql = '
        SELECT 
        *, 
        realisasi_fisik_'.$bulan_pelaporan.' AS realisasi_fisik, 
        realisasi_keuangan_'.$bulan_pelaporan.' AS realisasi_keuangan 
        FROM daftar_pptk_realisasi
        ORDER BY realisasi_fisik';
      $query = $this->db->query($sql);
      return $query->result();
    }

    function get_kinerja_pptk_total($kode_pd, $kode_giat_btl)
    {
      $sql = '
        SELECT
        COUNT(DISTINCT a.nip_pptk) AS jumlah_pptk,
        SUM(b.pagu_giat) AS anggaran_yang_dikelola,
        COUNT(a.kode_giat) AS jumlah_kegiatan
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        a.kode_giat <> "'.$kode_giat_btl.'"';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }

    function get_kinerja_pptk_detail($kode_pd, $bulan_pelaporan, $kode_giat_btl, $nip_pptk)
    {
      $sql = '
        SELECT
        a.kode_giat,
        a.nama_giat,
        COUNT(b.kode_rek_belanja) AS jumlah_belanja,
        SUM(b.pagu_giat) AS pagu_giat,
        SUM(
          b.kf_'.$bulan_pelaporan.' * 
          ROUND(b.pagu_giat /
              (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
               FROM belanja AS x
               JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
               WHERE y.kode_giat = a.kode_giat),8)) AS realisasi_fisik,
        SUM(
          100 * 
          ROUND(
            b.kk_'.$bulan_pelaporan.' /
              (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
               FROM belanja AS x
               JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
               WHERE
               y.kode_giat = a.kode_giat),8)) AS realisasi_keuangan
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        a.kode_giat <> "'.$kode_giat_btl.'" AND
        a.nip_pptk = "'.$nip_pptk.'"
        GROUP BY a.kode_giat
        ORDER BY realisasi_fisik';
      $query = $this->db->query($sql);
        // echo "<pre>";
        // print_r($query->result());
        // echo "</pre>";
        // exit();
      return $query->result();
    }





    function get_kinerja_pptk_chart($kode_pd, $kode_giat_btl, $nip_pptk)
    {
      $sql = '
        SELECT
        a.kode_giat,
        a.nama_giat,
        COUNT(b.kode_rek_belanja) AS jumlah_belanja,
        SUM(b.pagu_giat) AS pagu_giat,
        SUM(b.kf_1 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_1,
        SUM(b.kf_2 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_2,
        SUM(b.kf_3 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_3,
        SUM(b.kf_4 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_4,
        SUM(b.kf_5 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_5,
        SUM(b.kf_6 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_6,
        SUM(b.kf_7 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_7,
        SUM(b.kf_8 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_8,
        SUM(b.kf_9 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_9,
        SUM(b.kf_10 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_10,
        SUM(b.kf_11 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_11,
        SUM(b.kf_12 * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )) AS realisasi_fisik_12,

        ROUND(SUM(100 * (b.kk_1 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_1,
        ROUND(SUM(100 * (b.kk_2 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_2,
        ROUND(SUM(100 * (b.kk_3 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_3,
        ROUND(SUM(100 * (b.kk_4 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_4,
        ROUND(SUM(100 * (b.kk_5 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_5,
        ROUND(SUM(100 * (b.kk_6 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_6,
        ROUND(SUM(100 * (b.kk_7 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_7,
        ROUND(SUM(100 * (b.kk_8 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_8,
        ROUND(SUM(100 * (b.kk_9 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_9,
        ROUND(SUM(100 * (b.kk_10 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_10,
        ROUND(SUM(100 * (b.kk_11 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_11,
        ROUND(SUM(100 * (b.kk_12 /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
                      JOIN program AS z ON y.kode_prog = z.kode_prog
           WHERE
              z.kode_pd = "'.$kode_pd.'" AND
              y.kode_giat <> "'.$kode_giat_btl.'" AND
              y.nip_pptk = "'.$nip_pptk.'")
           )),8) AS realisasi_keuangan_12
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        a.kode_giat <> "'.$kode_giat_btl.'" AND
        a.nip_pptk = "'.$nip_pptk.'"';
      $query = $this->db->query($sql);
        // echo "<pre>";
        // print_r($query->result());
        // echo "</pre>";
        // exit();
      return $query->result();
    }

    function get_kinerja_pptk_detail_total($kode_pd, $bulan_pelaporan, $kode_giat_btl, $nip_pptk)
    {
      $sql = '
        SELECT
        a.nip_pptk,
        c.nama_p,
        c.jabat_p,
        c.hp_p,
        c.foto_p,
        SUM(b.pagu_giat) AS anggaran_yang_dikelola,
        SUM(b.kf_'.$bulan_pelaporan.' * (b.pagu_giat /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON z.kode_prog = y.kode_prog
           WHERE
           y.nip_pptk = a.nip_pptk AND
           z.kode_pd = "'.$kode_pd.'" AND
           y.kode_giat <> "'.$kode_giat_btl.'")
           )) AS realisasi_fisik,
        SUM(100 * ROUND(b.kk_'.$bulan_pelaporan.' /
          (SELECT SUM(x.pagu_giat) AS anggaran_yang_dikelola
           FROM belanja AS x
           JOIN kegiatan AS y ON x.kode_giat = y.kode_giat
           JOIN program AS z ON z.kode_prog = y.kode_prog
           WHERE
           y.nip_pptk = a.nip_pptk AND
           z.kode_pd = "'.$kode_pd.'" AND
           y.kode_giat <> "'.$kode_giat_btl.'")
           ,8)) AS realisasi_keuangan
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        a.kode_giat <> "'.$kode_giat_btl.'" AND
        a.nip_pptk = "'.$nip_pptk.'"';
      $query = $this->db->query($sql);
        // echo "<pre>";
        // print_r($query->result());
        // echo "</pre>";
        // exit();
      return $query->result();
    }

    function get_kinerja_pptk_terendah_fisik($kode_pd, $bulan_pelaporan, $kode_giat_btl)
    {
      $sql = '
        SELECT 
        *, 
        realisasi_fisik_'.$bulan_pelaporan.' AS realisasi_fisik, 
        realisasi_keuangan_'.$bulan_pelaporan.' AS realisasi_keuangan 
        FROM daftar_pptk_realisasi
        WHERE kode_pd = "'.$kode_pd.'"
        ORDER BY realisasi_fisik';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }

    function get_kinerja_pptk_terendah_keuangan($kode_pd, $bulan_pelaporan, $kode_giat_btl)
    {
      $sql = '
        SELECT 
        *, 
        realisasi_fisik_'.$bulan_pelaporan.' AS realisasi_fisik, 
        realisasi_keuangan_'.$bulan_pelaporan.' AS realisasi_keuangan 
        FROM daftar_pptk_realisasi
        WHERE kode_pd = "'.$kode_pd.'"
        ORDER BY realisasi_keuangan';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }

    function get_kinerja_pptk_tertinggi_fisik($kode_pd, $bulan_pelaporan, $kode_giat_btl)
    {
      $sql = '
        SELECT 
        *, 
        realisasi_fisik_'.$bulan_pelaporan.' AS realisasi_fisik, 
        realisasi_keuangan_'.$bulan_pelaporan.' AS realisasi_keuangan 
        FROM daftar_pptk_realisasi
        WHERE kode_pd = "'.$kode_pd.'"
        ORDER BY realisasi_fisik DESC';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }

    function get_kinerja_pptk_tertinggi_keuangan($kode_pd, $bulan_pelaporan, $kode_giat_btl)
    {
      $sql = '
        SELECT 
        *, 
        realisasi_fisik_'.$bulan_pelaporan.' AS realisasi_fisik, 
        realisasi_keuangan_'.$bulan_pelaporan.' AS realisasi_keuangan 
        FROM daftar_pptk_realisasi
        WHERE kode_pd = "'.$kode_pd.'"
        ORDER BY realisasi_keuangan DESC';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }

    function get_laporan_realisasi_kegiatan($bulan_pelaporan,$kode_giat)
    {
      $sql = '
        SELECT
          b.kode_rek_belanja,
          b.jenis_kegiatan,
          b.nama_belanja,
          b.pagu_giat,
          b.kf_'.$bulan_pelaporan.' AS realisasi_fisik,
          b.kk_'.$bulan_pelaporan.' AS realisasi_keuangan
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        WHERE a.kode_giat = "'.$kode_giat.'"
        ORDER BY jenis_kegiatan DESC, kode_rek_belanja';
      $query = $this->db->query($sql);
      return $query->result();
    }

    function get_laporan_realisasi_kegiatan_chart($kode_giat)
    {
      $sql = '
          SELECT
          a.kode_giat,
            a.nama_giat,
            SUM(b.pagu_giat) AS pagu_total,
            SUM(b.kf_1 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_1,
            SUM(b.kf_2 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_2,
            SUM(b.kf_3 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_3,
            SUM(b.kf_4 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_4,
            SUM(b.kf_5 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_5,
            SUM(b.kf_6 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_6,
            SUM(b.kf_7 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_7,
            SUM(b.kf_8 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_8,
            SUM(b.kf_9 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_9,
            SUM(b.kf_10 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_10,
            SUM(b.kf_11 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_11,
            SUM(b.kf_12 * (b.pagu_giat /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_fisik_12,
            SUM(100 * (b.kk_1 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_1,
            SUM(100 * (b.kk_2 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_2,
            SUM(100 * (b.kk_3 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_3,
            SUM(100 * (b.kk_4 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_4,
            SUM(100 * (b.kk_5 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_5,
            ROUND(SUM(100 * (b.kk_6 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )),8) AS realisasi_keuangan_6,
            SUM(100 * (b.kk_7 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_7,
            SUM(100 * (b.kk_8 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_8,
            SUM(100 * (b.kk_9 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_9,
            SUM(100 * (b.kk_10 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_10,
            SUM(100 * (b.kk_11 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_11,
            SUM(100 * (b.kk_12 /
              (SELECT SUM(pagu_giat) FROM belanja WHERE kode_giat = "'.$kode_giat.'")
            )) AS realisasi_keuangan_12
          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          WHERE a.kode_giat = "'.$kode_giat.'"
          ORDER BY jenis_kegiatan DESC, kode_rek_belanja
        ';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }

    function get_laporan_jenis_pengadaan($kode_pd)
    {
      $sql = '
        SELECT
          a.nip_pptk,
          c.nama_p,
          c.jabat_p,
          c.hp_p,
          c.foto_p,
          COUNT(b.jenis_kegiatan) AS total_paket_pengadaan,
          SUM(IF(b.jenis_pengadaan="Barang",1,0)) AS total_barang,
          SUM(IF(b.jenis_pengadaan="Konstruksi",1,0)) AS total_konstruksi,
          SUM(IF(b.jenis_pengadaan="Konsultan",1,0)) AS total_konsultan,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya",1,0)) AS total_lainnya
          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          JOIN pejabat AS c ON a.nip_pptk = c.nip_p
          JOIN program AS d ON a.kode_prog = d.kode_prog
          WHERE
          d.kode_pd = "'.$kode_pd.'" AND
          b.jenis_kegiatan = "pengadaan"        
          GROUP BY a.nip_pptk
        ';
      $query = $this->db->query($sql);
      return $query->result();
    }    

    function get_laporan_jenis_pengadaan_total($kode_pd)
    {
      $sql = '
        SELECT
          COUNT(DISTINCT a.nip_pptk) AS jumlah_pptk,
          COUNT(b.jenis_kegiatan) AS total_paket_pengadaan,
          SUM(IF(b.jenis_pengadaan="Barang",1,0)) AS total_barang,
          SUM(IF(b.jenis_pengadaan="Konstruksi",1,0)) AS total_konstruksi,
          SUM(IF(b.jenis_pengadaan="Konsultan",1,0)) AS total_konsultan,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya",1,0)) AS total_lainnya
          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          JOIN pejabat AS c ON a.nip_pptk = c.nip_p
          JOIN program AS d ON a.kode_prog = d.kode_prog
          WHERE
          d.kode_pd = "'.$kode_pd.'" AND
          b.jenis_kegiatan = "pengadaan"        
        ';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }     

    function get_laporan_jenis_pengadaan_detail($kode_pd,$nip_pptk)
    {
      $sql = '
        SELECT
          COUNT(a.nip_pptk) AS jumlah_pptk,
          c.nama_p,
          c.jabat_p,
          c.hp_p,
          c.foto_p,
          COUNT(b.jenis_kegiatan) AS total_paket_pengadaan,
          SUM(b.pagu_giat) AS total_pagu_pengadaan,
          SUM(IF(b.jenis_pengadaan="Barang",1,0)) AS total_barang,
          SUM(IF(b.jenis_pengadaan="Konstruksi",1,0)) AS total_konstruksi,
          SUM(IF(b.jenis_pengadaan="Konsultan",1,0)) AS total_konsultan,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya",1,0)) AS total_lainnya
          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          JOIN pejabat AS c ON a.nip_pptk = c.nip_p
          JOIN program AS d ON a.kode_prog = d.kode_prog
          WHERE
          d.kode_pd = "'.$kode_pd.'" AND
          b.jenis_kegiatan = "pengadaan" AND
          a.nip_pptk = "'.$nip_pptk.'"       
        ';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }     

    function get_laporan_jenis_pengadaan_detail_tabel($kode_pd,$nip_pptk)
    {
      $sql = '
        SELECT
          a.kode_giat,
          a.nama_giat,
          b.kode_rek_belanja,
          b.nama_belanja, 
          b.nama_paket_pengadaan, 
          b.pagu_giat,
          b.jenis_pengadaan,
          b.nip_ppk,
          c.nama_p,
          c.jabat_p,
          c.hp_p,
          c.foto_p         
          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          JOIN pejabat AS c ON b.nip_ppk = c.nip_p
          JOIN program AS d ON a.kode_prog = d.kode_prog
          WHERE
          d.kode_pd = "'.$kode_pd.'" AND
          b.jenis_kegiatan = "pengadaan" AND
          a.nip_pptk = "'.$nip_pptk.'"       
        ';
      $query = $this->db->query($sql);
      return $query->result();
    }       

    function get_laporan_metode_pemilihan_penyedia_barang($kode_pd)
    {
      $sql = '
        SELECT
        b.jenis_pengadaan,
        a.nip_pptk,
        c.nama_p,
        c.jabat_p,
        c.hp_p,
        c.foto_p,
        SUM(IF(b.metode_pemilihan_peny="LU",1,0)) AS barang_LU,
        SUM(IF(b.metode_pemilihan_peny="LS",1,0)) AS barang_LS,
        SUM(IF(b.metode_pemilihan_peny="PL",1,0)) AS barang_PL,
        SUM(IF(b.metode_pemilihan_peny="PK",1,0)) AS barang_PK,
        SUM(IF(b.metode_pemilihan_peny="SY",1,0)) AS barang_SY
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        b.jenis_kegiatan = "pengadaan" AND   
        b.jenis_pengadaan = "Barang"     
        GROUP BY a.nip_pptk
        ORDER BY a.nip_pptk;
        ';
      $query = $this->db->query($sql);
      return $query->result();
    } 

    function get_laporan_metode_pemilihan_penyedia_konstruksi($kode_pd)
    {
      $sql = '
        SELECT
        b.jenis_pengadaan,
        a.nip_pptk,
        c.nama_p,
        c.jabat_p,
        c.hp_p,
        c.foto_p,
        SUM(IF(b.metode_pemilihan_peny="LU",1,0)) AS konstruksi_LU,
        SUM(IF(b.metode_pemilihan_peny="LT",1,0)) AS konstruksi_LT,
        SUM(IF(b.metode_pemilihan_peny="PML",1,0)) AS konstruksi_PML,
        SUM(IF(b.metode_pemilihan_peny="PK",1,0)) AS konstruksi_PK,
        SUM(IF(b.metode_pemilihan_peny="PL",1,0)) AS konstruksi_PL
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        b.jenis_kegiatan = "pengadaan" AND   
        b.jenis_pengadaan = "Konstruksi"     
        GROUP BY a.nip_pptk
        ORDER BY a.nip_pptk;
        ';
      $query = $this->db->query($sql);
      return $query->result();
    }     

    function get_laporan_metode_pemilihan_penyedia_konsultan($kode_pd)
    {
      $sql = '
        SELECT
        b.jenis_pengadaan,
        a.nip_pptk,
        c.nama_p,
        c.jabat_p,
        c.hp_p,
        c.foto_p,
        SUM(IF(b.metode_pemilihan_peny="SU",1,0)) AS konsultan_SU,
        SUM(IF(b.metode_pemilihan_peny="SS",1,0)) AS konsultan_SS,
        SUM(IF(b.metode_pemilihan_peny="PK",1,0)) AS konsultan_PK,
        SUM(IF(b.metode_pemilihan_peny="PL",1,0)) AS konsultan_PL,
        SUM(IF(b.metode_pemilihan_peny="SY",1,0)) AS konsultan_SY
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        b.jenis_kegiatan = "pengadaan" AND   
        b.jenis_pengadaan = "Konsultan"     
        GROUP BY a.nip_pptk
        ORDER BY a.nip_pptk;
        ';
      $query = $this->db->query($sql);
      return $query->result();
    }

    function get_laporan_metode_pemilihan_penyedia_jasa_lainnya($kode_pd)
    {
      $sql = '
        SELECT
        b.jenis_pengadaan,
        a.nip_pptk,
        c.nama_p,
        c.jabat_p,
        c.hp_p,
        c.foto_p,
        SUM(IF(b.metode_pemilihan_peny="LU",1,0)) AS jasa_lainnya_LU,
        SUM(IF(b.metode_pemilihan_peny="LS",1,0)) AS jasa_lainnya_LS,
        SUM(IF(b.metode_pemilihan_peny="PK",1,0)) AS jasa_lainnya_PK,
        SUM(IF(b.metode_pemilihan_peny="PL",1,0)) AS jasa_lainnya_PL,
        SUM(IF(b.metode_pemilihan_peny="SY",1,0)) AS jasa_lainnya_SY
        FROM kegiatan AS a
        JOIN belanja AS b ON a.kode_giat = b.kode_giat
        JOIN pejabat AS c ON a.nip_pptk = c.nip_p
        JOIN program AS d ON a.kode_prog = d.kode_prog
        WHERE
        d.kode_pd = "'.$kode_pd.'" AND
        b.jenis_kegiatan = "pengadaan" AND   
        b.jenis_pengadaan = "Jasa lainnya"     
        GROUP BY a.nip_pptk
        ORDER BY a.nip_pptk;
        ';
      $query = $this->db->query($sql);
      return $query->result();
    }    

    function get_laporan_metode_pemilihan_penyedia_detail_pptk($kode_pd,$nip_pptk)
    {
      $sql = '
        SELECT
          c.nama_p,
          c.jabat_p,
          c.hp_p,
          c.foto_p,
          COUNT(b.jenis_kegiatan) AS total_paket_pengadaan,
          SUM(b.pagu_giat) AS total_pagu_pengadaan,

          SUM(IF(b.jenis_pengadaan="Barang",1,0)) AS total_barang,
          SUM(IF(b.jenis_pengadaan="Barang",b.pagu_giat,0)) AS pagu_total_barang,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="LU",1,0)) AS barang_LU,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="LU",b.pagu_giat,0)) AS pagu_barang_LU,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="LS",1,0)) AS barang_LS,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="LS",b.pagu_giat,0)) AS pagu_barang_LS,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="PL",1,0)) AS barang_PL,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="PL",b.pagu_giat,0)) AS pagu_barang_PL,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="PK",1,0)) AS barang_PK,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="PK",b.pagu_giat,0)) AS pagu_barang_PK,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="SY",1,0)) AS barang_SY,
          SUM(IF(b.jenis_pengadaan="Barang" AND b.metode_pemilihan_peny="SY",b.pagu_giat,0)) AS pagu_barang_SY,

          SUM(IF(b.jenis_pengadaan="Konstruksi",1,0)) AS total_konstruksi,
          SUM(IF(b.jenis_pengadaan="Konstruksi",b.pagu_giat,0)) AS pagu_total_konstruksi,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="LU",1,0)) AS konstruksi_LU,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="LU",b.pagu_giat,0)) AS pagu_konstruksi_LU,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="LT",1,0)) AS konstruksi_LT,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="LT",b.pagu_giat,0)) AS pagu_konstruksi_LT,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="PML",1,0)) AS konstruksi_PML,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="PML",b.pagu_giat,0)) AS pagu_konstruksi_PML,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="PK",1,0)) AS konstruksi_PK,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="PK",b.pagu_giat,0)) AS pagu_konstruksi_PK,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="PL",1,0)) AS konstruksi_PL,
          SUM(IF(b.jenis_pengadaan="Konstruksi" AND b.metode_pemilihan_peny="PL",b.pagu_giat,0)) AS pagu_konstruksi_PL,

          SUM(IF(b.jenis_pengadaan="Konsultan",1,0)) AS total_konsultan,
          SUM(IF(b.jenis_pengadaan="Konsultan",b.pagu_giat,0)) AS pagu_total_konsultan,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="SU",1,0)) AS konsultan_SU,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="SS",1,0)) AS konsultan_SS,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="PK",1,0)) AS konsultan_PK,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="PL",1,0)) AS konsultan_PL,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="SY",1,0)) AS konsultan_SY,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="SU",b.pagu_giat,0)) AS pagu_konsultan_SU,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="SS",b.pagu_giat,0)) AS pagu_konsultan_SS,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="PK",b.pagu_giat,0)) AS pagu_konsultan_PK,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="PL",b.pagu_giat,0)) AS pagu_konsultan_PL,
          SUM(IF(b.jenis_pengadaan="Konsultan" AND b.metode_pemilihan_peny="SY",b.pagu_giat,0)) AS pagu_konsultan_SY,

          SUM(IF(b.jenis_pengadaan="Jasa lainnya",1,0)) AS total_jasa_lainnya,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya",b.pagu_giat,0)) AS pagu_total_jasa_lainnya,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="LU",1,0)) AS jasa_lainnya_LU,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="LS",1,0)) AS jasa_lainnya_LS,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="PK",1,0)) AS jasa_lainnya_PK,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="PL",1,0)) AS jasa_lainnya_PL,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="SY",1,0)) AS jasa_lainnya_SY,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="LU",b.pagu_giat,0)) AS pagu_jasa_lainnya_LU,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="LS",b.pagu_giat,0)) AS pagu_jasa_lainnya_LS,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="PK",b.pagu_giat,0)) AS pagu_jasa_lainnya_PK,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="PL",b.pagu_giat,0)) AS pagu_jasa_lainnya_PL,
          SUM(IF(b.jenis_pengadaan="Jasa lainnya" AND b.metode_pemilihan_peny="SY",b.pagu_giat,0)) AS pagu_jasa_lainnya_SY

          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          JOIN pejabat AS c ON a.nip_pptk = c.nip_p
          JOIN program AS d ON a.kode_prog = d.kode_prog
          WHERE
          d.kode_pd = "'.$kode_pd.'" AND
          b.jenis_kegiatan = "pengadaan" AND
          a.nip_pptk = "'.$nip_pptk.'"       
        ';
      $query = $this->db->query($sql);
      return $query->result()[0];
    }        

    function get_laporan_metode_pemilihan_penyedia_detail_pptk_tabel($kode_pd,$nip_pptk)
    {
      $sql = '
        SELECT
          a.kode_giat,
          a.nama_giat,
          b.kode_rek_belanja,
          b.nama_belanja, 
          b.nama_paket_pengadaan, 
          b.pagu_giat,
          b.jenis_pengadaan,
          b.metode_pemilihan_peny,
          b.nip_ppk,
          c.nama_p,
          c.jabat_p,
          c.hp_p,
          c.foto_p         
          FROM kegiatan AS a
          JOIN belanja AS b ON a.kode_giat = b.kode_giat
          JOIN pejabat AS c ON b.nip_ppk = c.nip_p
          JOIN program AS d ON a.kode_prog = d.kode_prog
          WHERE
          d.kode_pd = "'.$kode_pd.'" AND
          b.jenis_kegiatan = "pengadaan" AND
          a.nip_pptk = "'.$nip_pptk.'"
          ORDER BY b.jenis_pengadaan      
        ';
      $query = $this->db->query($sql);
      return $query->result();
    } 

}
