<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Pejabat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pejabat by nip_p
     */
    function get_p($nip_p)
    {
        return $this->db->get_where('pejabat',array('nip_p'=>$nip_p))->row_array();
    }

    /*
     * Get all pejabat
     */
    function get_all_p($kode_pd)
    {
        $this->db->order_by('urutan_p');
        return $this->db->get_where('pejabat',array('pejabat_pd'=>$kode_pd))->result_array();
    }

    function get_all_p_pphp($kode_pd,$kode_rek_belanja)
    {    
        $this->db->from('pejabat as a');      
        $this->db->where(array('a.pejabat_pd'=>$kode_pd));
        $this->db->where('a.nip_p NOT IN (SELECT nip_pphp FROM pphp WHERE kode_rek_belanja="'.$kode_rek_belanja.'")');
        return $this->db->get()->result_array();
    }

    /*
     * function to add new pejabat
     */
    function add_p($params)
    {
        $this->db->insert('pejabat',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update pejabat
     */
    function update_p($nip_p,$params)
    {
        $this->db->where('nip_p',$nip_p);
        $response = $this->db->update('pejabat',$params);
        if($response)
        {
            return "pejabat updated successfully";
        }
        else
        {
            return "Error occuring while updating pejabat";
        }
    }

    /*
     * function to delete pejabat
     */
    function delete_p($nip_p)
    {
        $response = $this->db->delete('pejabat',array('nip_p'=>$nip_p));
        if($response)
        {
            return "pejabat deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pejabat";
        }
    }

    function check_duplicate($nip_p)
    {
      $this->db->select('*');
      $this->db->from('pejabat');
      $this->db->where(array('nip_p'=>$nip_p));
      $query = $this->db->get();
      $count_row = $query->num_rows();
      if ($count_row > 0) {
          return FALSE;
       } else {
          return TRUE;
       }
    }
}
