<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pengaturan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengaturan by id
     */
    function get_pengaturan($id)
    {
        return $this->db->get_where('pengaturan',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all pengaturan
     */
    function get_all_pengaturan()
    {
        return $this->db->get('pengaturan')->result_array();
    }
    
    /*
     * function to add new pengaturan
     */
    function add_pengaturan($params)
    {
        $this->db->insert('pengaturan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengaturan
     */
    function update_pengaturan($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('pengaturan',$params);
        if($response)
        {
            return "pengaturan updated successfully";
        }
        else
        {
            return "Error occuring while updating pengaturan";
        }
    }
    
    /*
     * function to delete pengaturan
     */
    function delete_pengaturan($id)
    {
        $response = $this->db->delete('pengaturan',array('id'=>$id));
        if($response)
        {
            return "pengaturan deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pengaturan";
        }
    }
}
