<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pp_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pp by nip_pp
     */
    function get_pp($nip_pp)
    {
        return $this->db->get_where('pp',array('nip_pp'=>$nip_pp))->row_array();
    }
    
    /*
     * Get all pp
     */
    function get_all_pp()
    {
        return $this->db->get('pp')->result_array();
    }
    
    /*
     * function to add new pp
     */
    function add_pp($params)
    {
        $this->db->insert('pp',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pp
     */
    function update_pp($nip_pp,$params)
    {
        $this->db->where('nip_pp',$nip_pp);
        $response = $this->db->update('pp',$params);
        if($response)
        {
            return "pp updated successfully";
        }
        else
        {
            return "Error occuring while updating pp";
        }
    }
    
    /*
     * function to delete pp
     */
    function delete_pp($nip_pp)
    {
        $response = $this->db->delete('pp',array('nip_pp'=>$nip_pp));
        if($response)
        {
            return "pp deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pp";
        }
    }
}
