<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Ppk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ppk by nip_ppk
     */
    function get_ppk($nip_ppk)
    {
        return $this->db->get_where('ppk',array('nip_ppk'=>$nip_ppk))->row_array();
    }
    
    /*
     * Get all ppk
     */
    function get_all_ppk()
    {
        return $this->db->get('ppk')->result_array();
    }
    
    /*
     * function to add new ppk
     */
    function add_ppk($params)
    {
        $this->db->insert('ppk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ppk
     */
    function update_ppk($nip_ppk,$params)
    {
        $this->db->where('nip_ppk',$nip_ppk);
        $response = $this->db->update('ppk',$params);
        if($response)
        {
            return "ppk updated successfully";
        }
        else
        {
            return "Error occuring while updating ppk";
        }
    }
    
    /*
     * function to delete ppk
     */
    function delete_ppk($nip_ppk)
    {
        $response = $this->db->delete('ppk',array('nip_ppk'=>$nip_ppk));
        if($response)
        {
            return "ppk deleted successfully";
        }
        else
        {
            return "Error occuring while deleting ppk";
        }
    }
}
