<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pptk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pptk by nip_pptk
     */
    function get_pptk($nip_pptk)
    {
        return $this->db->get_where('pptk',array('nip_pptk'=>$nip_pptk))->row_array();
    }
    
    /*
     * Get all pptk
     */
    function get_all_pptk()
    {
        return $this->db->get('pptk')->result_array();
    }
    
    /*
     * function to add new pptk
     */
    function add_pptk($params)
    {
        $this->db->insert('pptk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pptk
     */
    function update_pptk($nip_pptk,$params)
    {
        $this->db->where('nip_pptk',$nip_pptk);
        $response = $this->db->update('pptk',$params);
        if($response)
        {
            return "pptk updated successfully";
        }
        else
        {
            return "Error occuring while updating pptk";
        }
    }
    
    /*
     * function to delete pptk
     */
    function delete_pptk($nip_pptk)
    {
        $response = $this->db->delete('pptk',array('nip_pptk'=>$nip_pptk));
        if($response)
        {
            return "pptk deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pptk";
        }
    }
}
