# anggaran total, anggaran BTL dan anggaran BL
SELECT 
   @anggaran_total := SUM(a.pagu_giat) AS anggaran_total,
   @anggaran_btl := SUM(IF(b.kode_giat = d.kode_giat_btl, a.pagu_giat, 0)) AS anggaran_btl,
   @anggaran_bl := SUM(IF(b.kode_giat <> d.kode_giat_btl OR 
          d.kode_giat_btl = "" OR 
          d.kode_giat_btl IS NULL, 
          a.pagu_giat, 0
         )
       ) AS anggaran_bl        
FROM belanja AS a
JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
JOIN program AS c ON b.kode_prog = c.kode_prog
JOIN pd AS d ON c.kode_pd = d.kode_pd;

# hitung persen BL dan BTL
SET @anggaran_bl_persen = (@anggaran_bl / @anggaran_total)*100;
SET @anggaran_btl_persen = (@anggaran_btl / @anggaran_total)*100;

# hitung jumlah belanja, kegiatan dan program
SELECT 
  @jumlah_belanja := COUNT(DISTINCT a.kode_rek_belanja) AS jumlah_belanja,
  @jumlah_kegiatan := COUNT(DISTINCT b.kode_giat) AS jumlah_kegiatan,
  @jumlah_program := COUNT(DISTINCT c.kode_prog) AS jumlah_program      
FROM belanja AS a
JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
JOIN program AS c ON b.kode_prog = c.kode_prog
JOIN pd AS d ON c.kode_pd = d.kode_pd
WHERE b.kode_giat <> d.kode_giat_btl OR d.kode_giat_btl = "" OR d.kode_giat_btl IS NULL;

# dapatkan target dan hitung realisasi untuk BL dan BTL
DROP TEMPORARY TABLE IF EXISTS target_realisasi_pd;
CREATE TEMPORARY TABLE target_realisasi_pd AS
SELECT 
  d.kode_pd,
  SUM(a.pagu_giat) AS anggaran_total,
  SUM(IF(b.kode_giat = d.kode_giat_btl, a.pagu_giat, 0)) AS anggaran_btl,
  SUM(IF(b.kode_giat <> d.kode_giat_btl OR 
         d.kode_giat_btl = "" OR 
         d.kode_giat_btl IS NULL, 
         a.pagu_giat, 0)) AS anggaran_bl, 
  # target fisik BTL
  d.btl_tf_1,d.btl_tf_2,d.btl_tf_3,d.btl_tf_4,d.btl_tf_5,d.btl_tf_6,d.btl_tf_7,d.btl_tf_8,
  d.btl_tf_9,d.btl_tf_10,d.btl_tf_11,d.btl_tf_12,
  # target keuangan BTL
  d.btl_tk_1,d.btl_tk_2,d.btl_tk_3,d.btl_tk_4,d.btl_tk_5,d.btl_tk_6,d.btl_tk_7,d.btl_tk_8,
  d.btl_tk_9,d.btl_tk_10,d.btl_tk_11,d.btl_tk_12,
  # realisasi fisik BTL
  d.btl_rf_1,d.btl_rf_2,d.btl_rf_3,d.btl_rf_4,d.btl_rf_5,d.btl_rf_6,d.btl_rf_7,d.btl_rf_8,
  d.btl_rf_9,d.btl_rf_10,d.btl_rf_11,d.btl_rf_12,
  # deviasi fisik BTL
  d.btl_rf_1  - d.btl_tf_1  AS btl_rf_1_dev,
  d.btl_rf_2  - d.btl_tf_2  AS btl_rf_2_dev,
  d.btl_rf_3  - d.btl_tf_3  AS btl_rf_3_dev,
  d.btl_rf_4  - d.btl_tf_4  AS btl_rf_4_dev,
  d.btl_rf_5  - d.btl_tf_5  AS btl_rf_5_dev,
  d.btl_rf_6  - d.btl_tf_6  AS btl_rf_6_dev,
  d.btl_rf_7  - d.btl_tf_7  AS btl_rf_7_dev,
  d.btl_rf_8  - d.btl_tf_8  AS btl_rf_8_dev,
  d.btl_rf_9  - d.btl_tf_9  AS btl_rf_9_dev,
  d.btl_rf_10 - d.btl_tf_10 AS btl_rf_10_dev,
  d.btl_rf_11 - d.btl_tf_11 AS btl_rf_11_dev,
  d.btl_rf_12 - d.btl_tf_12 AS btl_rf_12_dev,
  # realisasi keuangan BTL
  d.btl_rk_1,d.btl_rk_2,d.btl_rk_3,d.btl_rk_4,d.btl_rk_5,d.btl_rk_6,d.btl_rk_7,d.btl_rk_8,
  d.btl_rk_9,d.btl_rk_10,d.btl_rk_11,d.btl_rk_12,   
  # deviasi keuangan BTL
  d.btl_rk_1  - d.btl_tk_1  AS btl_rk_1_dev,
  d.btl_rk_2  - d.btl_tk_2  AS btl_rk_2_dev,
  d.btl_rk_3  - d.btl_tk_3  AS btl_rk_3_dev,
  d.btl_rk_4  - d.btl_tk_4  AS btl_rk_4_dev,
  d.btl_rk_5  - d.btl_tk_5  AS btl_rk_5_dev,
  d.btl_rk_6  - d.btl_tk_6  AS btl_rk_6_dev,
  d.btl_rk_7  - d.btl_tk_7  AS btl_rk_7_dev,
  d.btl_rk_8  - d.btl_tk_8  AS btl_rk_8_dev,
  d.btl_rk_9  - d.btl_tk_9  AS btl_rk_9_dev,
  d.btl_rk_10 - d.btl_tk_10 AS btl_rk_10_dev,
  d.btl_rk_11 - d.btl_tk_11 AS btl_rk_11_dev,
  d.btl_rk_12 - d.btl_tk_12 AS btl_rk_12_dev,  
  # target fisik BL       
  d.tf_1,d.tf_2,d.tf_3,d.tf_4,d.tf_5,d.tf_6,d.tf_7,d.tf_8,d.tf_9,d.tf_10,d.tf_11,d.tf_12,
  # target keuangan BL
  d.tk_1,d.tk_2,d.tk_3,d.tk_4,d.tk_5,d.tk_6,d.tk_7,d.tk_8,d.tk_9,d.tk_10,d.tk_11,d.tk_12,
  # realisasi fisik BL
  SUM(a.pagu_giat * a.kf_1 ) AS rf_1 ,
  SUM(a.pagu_giat * a.kf_2 ) AS rf_2 ,
  SUM(a.pagu_giat * a.kf_3 ) AS rf_3 ,
  SUM(a.pagu_giat * a.kf_4 ) AS rf_4 ,
  SUM(a.pagu_giat * a.kf_5 ) AS rf_5 ,
  SUM(a.pagu_giat * a.kf_6 ) AS rf_6 ,
  SUM(a.pagu_giat * a.kf_7 ) AS rf_7 ,
  SUM(a.pagu_giat * a.kf_8 ) AS rf_8 ,
  SUM(a.pagu_giat * a.kf_9 ) AS rf_9 ,
  SUM(a.pagu_giat * a.kf_10) AS rf_10,
  SUM(a.pagu_giat * a.kf_11) AS rf_11,
  SUM(a.pagu_giat * a.kf_12) AS rf_12,
  SUM(a.kk_1 ) AS rk_1 ,
  SUM(a.kk_2 ) AS rk_2 ,
  SUM(a.kk_3 ) AS rk_3 ,
  SUM(a.kk_4 ) AS rk_4 ,
  SUM(a.kk_5 ) AS rk_5 ,
  SUM(a.kk_6 ) AS rk_6 ,
  SUM(a.kk_7 ) AS rk_7 ,
  SUM(a.kk_8 ) AS rk_8 ,
  SUM(a.kk_9 ) AS rk_9 ,
  SUM(a.kk_10) AS rk_10,
  SUM(a.kk_11) AS rk_11,
  SUM(a.kk_12) AS rk_12,
  (SUM(a.kk_1 )/SUM(a.pagu_giat))*100 AS rkp_1 ,
  (SUM(a.kk_2 )/SUM(a.pagu_giat))*100 AS rkp_2 ,
  (SUM(a.kk_3 )/SUM(a.pagu_giat))*100 AS rkp_3 ,
  (SUM(a.kk_4 )/SUM(a.pagu_giat))*100 AS rkp_4 ,
  (SUM(a.kk_5 )/SUM(a.pagu_giat))*100 AS rkp_5 ,
  (SUM(a.kk_6 )/SUM(a.pagu_giat))*100 AS rkp_6 ,
  (SUM(a.kk_7 )/SUM(a.pagu_giat))*100 AS rkp_7 ,
  (SUM(a.kk_8 )/SUM(a.pagu_giat))*100 AS rkp_8 ,
  (SUM(a.kk_9 )/SUM(a.pagu_giat))*100 AS rkp_9 ,
  (SUM(a.kk_10)/SUM(a.pagu_giat))*100 AS rkp_10,
  (SUM(a.kk_11)/SUM(a.pagu_giat))*100 AS rkp_11,
  (SUM(a.kk_12)/SUM(a.pagu_giat))*100 AS rkp_12
FROM belanja AS a
JOIN kegiatan AS b ON a.kode_giat = b.kode_giat
JOIN program AS c ON b.kode_prog = c.kode_prog
JOIN pd AS d ON c.kode_pd = d.kode_pd
GROUP BY d.kode_pd
ORDER BY d.kode_pd;

# hitung realisasi fisik BL (bagikan dengan anggaran BL)
UPDATE target_realisasi_pd
  SET 
  rf_1 = rf_1 / anggaran_bl,
  rf_2 = rf_2 / anggaran_bl,
  rf_3 = rf_3 / anggaran_bl,
  rf_4 = rf_4 / anggaran_bl,
  rf_5 = rf_5 / anggaran_bl,
  rf_6 = rf_6 / anggaran_bl,
  rf_7 = rf_7 / anggaran_bl,
  rf_8 = rf_8 / anggaran_bl,
  rf_9 = rf_9 / anggaran_bl,
  rf_10 = rf_10 / anggaran_bl,
  rf_11 = rf_11 / anggaran_bl,
  rf_12 = rf_12 / anggaran_bl;

# tambah kolom PERSENTASE realisasi keuangan BTL 
ALTER TABLE target_realisasi_pd 
  ADD COLUMN btl_tkp_12 FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_11 FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_10 FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_9  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_8  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_7  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_6  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_5  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_4  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_3  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_2  FLOAT AFTER btl_tk_12,
  ADD COLUMN btl_tkp_1  FLOAT AFTER btl_tk_12,

  ADD COLUMN btl_rkp_12 FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_11 FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_10 FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_9  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_8  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_7  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_6  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_5  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_4  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_3  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_2  FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_1  FLOAT AFTER btl_rk_12,

  ADD COLUMN btl_rkp_12_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_11_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_10_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_9_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_8_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_7_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_6_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_5_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_4_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_3_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_2_dev FLOAT AFTER btl_rk_12,
  ADD COLUMN btl_rkp_1_dev FLOAT AFTER btl_rk_12;  

UPDATE target_realisasi_pd
  SET 
  btl_tkp_1  = (btl_tk_1  / anggaran_btl) * 100,
  btl_tkp_2  = (btl_tk_2  / anggaran_btl) * 100,
  btl_tkp_3  = (btl_tk_3  / anggaran_btl) * 100,
  btl_tkp_4  = (btl_tk_4  / anggaran_btl) * 100,
  btl_tkp_5  = (btl_tk_5  / anggaran_btl) * 100,
  btl_tkp_6  = (btl_tk_6  / anggaran_btl) * 100,
  btl_tkp_7  = (btl_tk_7  / anggaran_btl) * 100,
  btl_tkp_8  = (btl_tk_8  / anggaran_btl) * 100,
  btl_tkp_9  = (btl_tk_9  / anggaran_btl) * 100,
  btl_tkp_10 = (btl_tk_10 / anggaran_btl) * 100,
  btl_tkp_11 = (btl_tk_11 / anggaran_btl) * 100,
  btl_tkp_12 = (btl_tk_12 / anggaran_btl) * 100,

  btl_rkp_1  = (btl_rk_1  / anggaran_btl) * 100,
  btl_rkp_2  = (btl_rk_2  / anggaran_btl) * 100,
  btl_rkp_3  = (btl_rk_3  / anggaran_btl) * 100,
  btl_rkp_4  = (btl_rk_4  / anggaran_btl) * 100,
  btl_rkp_5  = (btl_rk_5  / anggaran_btl) * 100,
  btl_rkp_6  = (btl_rk_6  / anggaran_btl) * 100,
  btl_rkp_7  = (btl_rk_7  / anggaran_btl) * 100,
  btl_rkp_8  = (btl_rk_8  / anggaran_btl) * 100,
  btl_rkp_9  = (btl_rk_9  / anggaran_btl) * 100,
  btl_rkp_10 = (btl_rk_10 / anggaran_btl) * 100,
  btl_rkp_11 = (btl_rk_11 / anggaran_btl) * 100,
  btl_rkp_12 = (btl_rk_12 / anggaran_btl) * 100,

  btl_rkp_1_dev  = ((btl_rk_1  / anggaran_btl) * 100) - ((btl_tk_1  / anggaran_btl) * 100),
  btl_rkp_2_dev  = ((btl_rk_2  / anggaran_btl) * 100) - ((btl_tk_2  / anggaran_btl) * 100),
  btl_rkp_3_dev  = ((btl_rk_3  / anggaran_btl) * 100) - ((btl_tk_3  / anggaran_btl) * 100),
  btl_rkp_4_dev  = ((btl_rk_4  / anggaran_btl) * 100) - ((btl_tk_4  / anggaran_btl) * 100),
  btl_rkp_5_dev  = ((btl_rk_5  / anggaran_btl) * 100) - ((btl_tk_5  / anggaran_btl) * 100),
  btl_rkp_6_dev  = ((btl_rk_6  / anggaran_btl) * 100) - ((btl_tk_6  / anggaran_btl) * 100),
  btl_rkp_7_dev  = ((btl_rk_7  / anggaran_btl) * 100) - ((btl_tk_7  / anggaran_btl) * 100),
  btl_rkp_8_dev  = ((btl_rk_8  / anggaran_btl) * 100) - ((btl_tk_8  / anggaran_btl) * 100),
  btl_rkp_9_dev  = ((btl_rk_9  / anggaran_btl) * 100) - ((btl_tk_9  / anggaran_btl) * 100),
  btl_rkp_10_dev = ((btl_rk_10 / anggaran_btl) * 100) - ((btl_tk_10 / anggaran_btl) * 100),
  btl_rkp_11_dev = ((btl_rk_11 / anggaran_btl) * 100) - ((btl_tk_11 / anggaran_btl) * 100),
  btl_rkp_12_dev = ((btl_rk_12 / anggaran_btl) * 100) - ((btl_tk_12 / anggaran_btl) * 100);

ALTER TABLE target_realisasi_pd 
  # persentase target keuangan BL
  ADD COLUMN tkp_12 FLOAT AFTER tk_12,
  ADD COLUMN tkp_11 FLOAT AFTER tk_12,
  ADD COLUMN tkp_10 FLOAT AFTER tk_12,
  ADD COLUMN tkp_9  FLOAT AFTER tk_12,
  ADD COLUMN tkp_8  FLOAT AFTER tk_12,
  ADD COLUMN tkp_7  FLOAT AFTER tk_12,
  ADD COLUMN tkp_6  FLOAT AFTER tk_12,
  ADD COLUMN tkp_5  FLOAT AFTER tk_12,
  ADD COLUMN tkp_4  FLOAT AFTER tk_12,
  ADD COLUMN tkp_3  FLOAT AFTER tk_12,
  ADD COLUMN tkp_2  FLOAT AFTER tk_12,
  ADD COLUMN tkp_1  FLOAT AFTER tk_12,
  # deviasi realisasi keuangan BL
  ADD COLUMN rkp_12_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_11_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_10_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_9_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_8_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_7_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_6_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_5_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_4_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_3_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_2_dev FLOAT AFTER tk_12,
  ADD COLUMN rkp_1_dev FLOAT AFTER tk_12;  

UPDATE target_realisasi_pd
  SET 
  # persen target keuangan BL
  tkp_1  = (tk_1  / anggaran_bl) * 100,
  tkp_2  = (tk_2  / anggaran_bl) * 100,
  tkp_3  = (tk_3  / anggaran_bl) * 100,
  tkp_4  = (tk_4  / anggaran_bl) * 100,
  tkp_5  = (tk_5  / anggaran_bl) * 100,
  tkp_6  = (tk_6  / anggaran_bl) * 100,
  tkp_7  = (tk_7  / anggaran_bl) * 100,
  tkp_8  = (tk_8  / anggaran_bl) * 100,
  tkp_9  = (tk_9  / anggaran_bl) * 100,
  tkp_10 = (tk_10 / anggaran_bl) * 100,
  tkp_11 = (tk_11 / anggaran_bl) * 100,
  tkp_12 = (tk_12 / anggaran_bl) * 100,
  # persen deviasi realisasi keuangan BL
  rkp_1_dev = rkp_1  - ((tk_1  / anggaran_bl) * 100),
  rkp_2_dev = rkp_2  - ((tk_2  / anggaran_bl) * 100),
  rkp_3_dev = rkp_3  - ((tk_3  / anggaran_bl) * 100),
  rkp_4_dev = rkp_4  - ((tk_4  / anggaran_bl) * 100),
  rkp_5_dev = rkp_5  - ((tk_5  / anggaran_bl) * 100),
  rkp_6_dev = rkp_6  - ((tk_6  / anggaran_bl) * 100),
  rkp_7_dev = rkp_7  - ((tk_7  / anggaran_bl) * 100),
  rkp_8_dev = rkp_8  - ((tk_8  / anggaran_bl) * 100),
  rkp_9_dev = rkp_9  - ((tk_9  / anggaran_bl) * 100),
  rkp_10_dev = rkp_10 - ((tk_10 / anggaran_bl) * 100),
  rkp_11_dev = rkp_11 - ((tk_11 / anggaran_bl) * 100),
  rkp_12_dev = rkp_12 - ((tk_12 / anggaran_bl) * 100);

# SELECT * FROM target_realisasi_pd;

# tambahkan kolom realisasi fisik dan keuangan total PD (sesudah kolom Target keuangan BL)
ALTER TABLE target_realisasi_pd 
  ADD COLUMN tot_tf_1  FLOAT,
  ADD COLUMN tot_tf_2  FLOAT,
  ADD COLUMN tot_tf_3  FLOAT,
  ADD COLUMN tot_tf_4  FLOAT,
  ADD COLUMN tot_tf_5  FLOAT,
  ADD COLUMN tot_tf_6  FLOAT,
  ADD COLUMN tot_tf_7  FLOAT,
  ADD COLUMN tot_tf_8  FLOAT,
  ADD COLUMN tot_tf_9  FLOAT,
  ADD COLUMN tot_tf_10 FLOAT,
  ADD COLUMN tot_tf_11 FLOAT,    
  ADD COLUMN tot_tf_12 FLOAT,

  ADD COLUMN tot_tk_1  BIGINT,
  ADD COLUMN tot_tk_2  BIGINT,
  ADD COLUMN tot_tk_3  BIGINT,
  ADD COLUMN tot_tk_4  BIGINT,
  ADD COLUMN tot_tk_5  BIGINT,
  ADD COLUMN tot_tk_6  BIGINT,
  ADD COLUMN tot_tk_7  BIGINT,
  ADD COLUMN tot_tk_8  BIGINT,
  ADD COLUMN tot_tk_9  BIGINT,
  ADD COLUMN tot_tk_10  BIGINT,
  ADD COLUMN tot_tk_11  BIGINT,    
  ADD COLUMN tot_tk_12  BIGINT,

  ADD COLUMN tot_tkp_1  FLOAT,
  ADD COLUMN tot_tkp_2  FLOAT,
  ADD COLUMN tot_tkp_3  FLOAT,
  ADD COLUMN tot_tkp_4  FLOAT,
  ADD COLUMN tot_tkp_5  FLOAT,
  ADD COLUMN tot_tkp_6  FLOAT,
  ADD COLUMN tot_tkp_7  FLOAT,
  ADD COLUMN tot_tkp_8  FLOAT,
  ADD COLUMN tot_tkp_9  FLOAT,
  ADD COLUMN tot_tkp_10  FLOAT,
  ADD COLUMN tot_tkp_11  FLOAT,    
  ADD COLUMN tot_tkp_12  FLOAT,  

  ADD COLUMN tot_rf_1  FLOAT,
  ADD COLUMN tot_rf_2  FLOAT,
  ADD COLUMN tot_rf_3  FLOAT,
  ADD COLUMN tot_rf_4  FLOAT,
  ADD COLUMN tot_rf_5  FLOAT,
  ADD COLUMN tot_rf_6  FLOAT,
  ADD COLUMN tot_rf_7  FLOAT,
  ADD COLUMN tot_rf_8  FLOAT,
  ADD COLUMN tot_rf_9  FLOAT,
  ADD COLUMN tot_rf_10 FLOAT,
  ADD COLUMN tot_rf_11 FLOAT,    
  ADD COLUMN tot_rf_12 FLOAT,

  ADD COLUMN tot_rf_1_dev FLOAT,
  ADD COLUMN tot_rf_2_dev FLOAT,
  ADD COLUMN tot_rf_3_dev FLOAT,
  ADD COLUMN tot_rf_4_dev FLOAT,
  ADD COLUMN tot_rf_5_dev FLOAT,
  ADD COLUMN tot_rf_6_dev FLOAT,
  ADD COLUMN tot_rf_7_dev FLOAT,
  ADD COLUMN tot_rf_8_dev FLOAT,
  ADD COLUMN tot_rf_9_dev FLOAT,
  ADD COLUMN tot_rf_10_dev FLOAT,
  ADD COLUMN tot_rf_11_dev FLOAT,    
  ADD COLUMN tot_rf_12_dev FLOAT,

  ADD COLUMN tot_rk_1  BIGINT,
  ADD COLUMN tot_rk_2  BIGINT,
  ADD COLUMN tot_rk_3  BIGINT,
  ADD COLUMN tot_rk_4  BIGINT,
  ADD COLUMN tot_rk_5  BIGINT,
  ADD COLUMN tot_rk_6  BIGINT,
  ADD COLUMN tot_rk_7  BIGINT,
  ADD COLUMN tot_rk_8  BIGINT,
  ADD COLUMN tot_rk_9  BIGINT,
  ADD COLUMN tot_rk_10  BIGINT,
  ADD COLUMN tot_rk_11  BIGINT,    
  ADD COLUMN tot_rk_12  BIGINT,

  ADD COLUMN tot_rkp_1  FLOAT,
  ADD COLUMN tot_rkp_2  FLOAT,
  ADD COLUMN tot_rkp_3  FLOAT,
  ADD COLUMN tot_rkp_4  FLOAT,
  ADD COLUMN tot_rkp_5  FLOAT,
  ADD COLUMN tot_rkp_6  FLOAT,
  ADD COLUMN tot_rkp_7  FLOAT,
  ADD COLUMN tot_rkp_8  FLOAT,
  ADD COLUMN tot_rkp_9  FLOAT,
  ADD COLUMN tot_rkp_10  FLOAT,
  ADD COLUMN tot_rkp_11  FLOAT,    
  ADD COLUMN tot_rkp_12  FLOAT, 

  ADD COLUMN tot_rkp_1_dev  FLOAT,
  ADD COLUMN tot_rkp_2_dev  FLOAT,
  ADD COLUMN tot_rkp_3_dev  FLOAT,
  ADD COLUMN tot_rkp_4_dev  FLOAT,
  ADD COLUMN tot_rkp_5_dev  FLOAT,
  ADD COLUMN tot_rkp_6_dev  FLOAT,
  ADD COLUMN tot_rkp_7_dev  FLOAT,
  ADD COLUMN tot_rkp_8_dev  FLOAT,
  ADD COLUMN tot_rkp_9_dev  FLOAT,
  ADD COLUMN tot_rkp_10_dev  FLOAT,
  ADD COLUMN tot_rkp_11_dev  FLOAT,    
  ADD COLUMN tot_rkp_12_dev  FLOAT;   

UPDATE target_realisasi_pd
  SET 
  tot_tf_1  = ((anggaran_bl  / anggaran_total) *  tf_1)  + ((anggaran_btl  / anggaran_total) *  btl_tf_1) ,
  tot_tf_2  = ((anggaran_bl  / anggaran_total) *  tf_2)  + ((anggaran_btl  / anggaran_total) *  btl_tf_2) ,
  tot_tf_3  = ((anggaran_bl  / anggaran_total) *  tf_3)  + ((anggaran_btl  / anggaran_total) *  btl_tf_3) ,
  tot_tf_4  = ((anggaran_bl  / anggaran_total) *  tf_4)  + ((anggaran_btl  / anggaran_total) *  btl_tf_4) ,
  tot_tf_5  = ((anggaran_bl  / anggaran_total) *  tf_5)  + ((anggaran_btl  / anggaran_total) *  btl_tf_5) ,
  tot_tf_6  = ((anggaran_bl  / anggaran_total) *  tf_6)  + ((anggaran_btl  / anggaran_total) *  btl_tf_6) ,
  tot_tf_7  = ((anggaran_bl  / anggaran_total) *  tf_7)  + ((anggaran_btl  / anggaran_total) *  btl_tf_7) ,
  tot_tf_8  = ((anggaran_bl  / anggaran_total) *  tf_8)  + ((anggaran_btl  / anggaran_total) *  btl_tf_8) ,
  tot_tf_9  = ((anggaran_bl  / anggaran_total) *  tf_9)  + ((anggaran_btl  / anggaran_total) *  btl_tf_9) ,
  tot_tf_10 = ((anggaran_bl  / anggaran_total) *  tf_10) + ((anggaran_btl  / anggaran_total) *  btl_tf_10),
  tot_tf_11 = ((anggaran_bl  / anggaran_total) *  tf_11) + ((anggaran_btl  / anggaran_total) *  btl_tf_11),
  tot_tf_12 = ((anggaran_bl  / anggaran_total) *  tf_12) + ((anggaran_btl  / anggaran_total) *  btl_tf_12),
  tot_tk_1  = tk_1  + btl_tk_1 ,
  tot_tk_2  = tk_2  + btl_tk_2 ,
  tot_tk_3  = tk_3  + btl_tk_3 ,
  tot_tk_4  = tk_4  + btl_tk_4 ,
  tot_tk_5  = tk_5  + btl_tk_5 ,
  tot_tk_6  = tk_6  + btl_tk_6 ,
  tot_tk_7  = tk_7  + btl_tk_7 ,
  tot_tk_8  = tk_8  + btl_tk_8 ,
  tot_tk_9  = tk_9  + btl_tk_9 ,
  tot_tk_10 = tk_10 + btl_tk_10,
  tot_tk_11 = tk_11 + btl_tk_11,
  tot_tk_12 = tk_12 + btl_tk_12,
  tot_rf_1  = ((anggaran_bl  / anggaran_total) *  rf_1)  + ((anggaran_btl  / anggaran_total) *  btl_rf_1) ,
  tot_rf_2  = ((anggaran_bl  / anggaran_total) *  rf_2)  + ((anggaran_btl  / anggaran_total) *  btl_rf_2) ,
  tot_rf_3  = ((anggaran_bl  / anggaran_total) *  rf_3)  + ((anggaran_btl  / anggaran_total) *  btl_rf_3) ,
  tot_rf_4  = ((anggaran_bl  / anggaran_total) *  rf_4)  + ((anggaran_btl  / anggaran_total) *  btl_rf_4) ,
  tot_rf_5  = ((anggaran_bl  / anggaran_total) *  rf_5)  + ((anggaran_btl  / anggaran_total) *  btl_rf_5) ,
  tot_rf_6  = ((anggaran_bl  / anggaran_total) *  rf_6)  + ((anggaran_btl  / anggaran_total) *  btl_rf_6) ,
  tot_rf_7  = ((anggaran_bl  / anggaran_total) *  rf_7)  + ((anggaran_btl  / anggaran_total) *  btl_rf_7) ,
  tot_rf_8  = ((anggaran_bl  / anggaran_total) *  rf_8)  + ((anggaran_btl  / anggaran_total) *  btl_rf_8) ,
  tot_rf_9  = ((anggaran_bl  / anggaran_total) *  rf_9)  + ((anggaran_btl  / anggaran_total) *  btl_rf_9) ,
  tot_rf_10 = ((anggaran_bl  / anggaran_total) *  rf_10) + ((anggaran_btl  / anggaran_total) *  btl_rf_10),
  tot_rf_11 = ((anggaran_bl  / anggaran_total) *  rf_11) + ((anggaran_btl  / anggaran_total) *  btl_rf_11),
  tot_rf_12 = ((anggaran_bl  / anggaran_total) *  rf_12) + ((anggaran_btl  / anggaran_total) *  btl_rf_12),

  tot_rf_1_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_1)  + ((anggaran_btl  / anggaran_total) *  btl_rf_1)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_1)  + ((anggaran_btl  / anggaran_total) *  btl_tf_1)  ),
  tot_rf_2_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_2)  + ((anggaran_btl  / anggaran_total) *  btl_rf_2)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_2)  + ((anggaran_btl  / anggaran_total) *  btl_tf_2)  ),
  tot_rf_3_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_3)  + ((anggaran_btl  / anggaran_total) *  btl_rf_3)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_3)  + ((anggaran_btl  / anggaran_total) *  btl_tf_3)  ),
  tot_rf_4_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_4)  + ((anggaran_btl  / anggaran_total) *  btl_rf_4)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_4)  + ((anggaran_btl  / anggaran_total) *  btl_tf_4)  ),
  tot_rf_5_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_5)  + ((anggaran_btl  / anggaran_total) *  btl_rf_5)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_5)  + ((anggaran_btl  / anggaran_total) *  btl_tf_5)  ),
  tot_rf_6_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_6)  + ((anggaran_btl  / anggaran_total) *  btl_rf_6)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_6)  + ((anggaran_btl  / anggaran_total) *  btl_tf_6)  ),
  tot_rf_7_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_7)  + ((anggaran_btl  / anggaran_total) *  btl_rf_7)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_7)  + ((anggaran_btl  / anggaran_total) *  btl_tf_7)  ),
  tot_rf_8_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_8)  + ((anggaran_btl  / anggaran_total) *  btl_rf_8)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_8)  + ((anggaran_btl  / anggaran_total) *  btl_tf_8)  ),
  tot_rf_9_dev  = ( ((anggaran_bl  / anggaran_total) *  rf_9)  + ((anggaran_btl  / anggaran_total) *  btl_rf_9)  ) - ( ((anggaran_bl  / anggaran_total) *  tf_9)  + ((anggaran_btl  / anggaran_total) *  btl_tf_9)  ),
  tot_rf_10_dev = ( ((anggaran_bl  / anggaran_total) *  rf_10) + ((anggaran_btl  / anggaran_total) *  btl_rf_10) ) - ( ((anggaran_bl  / anggaran_total) *  tf_10) + ((anggaran_btl  / anggaran_total) *  btl_tf_10) ),
  tot_rf_11_dev = ( ((anggaran_bl  / anggaran_total) *  rf_11) + ((anggaran_btl  / anggaran_total) *  btl_rf_11) ) - ( ((anggaran_bl  / anggaran_total) *  tf_11) + ((anggaran_btl  / anggaran_total) *  btl_tf_11) ),
  tot_rf_12_dev = ( ((anggaran_bl  / anggaran_total) *  rf_12) + ((anggaran_btl  / anggaran_total) *  btl_rf_12) ) - ( ((anggaran_bl  / anggaran_total) *  tf_12) + ((anggaran_btl  / anggaran_total) *  btl_tf_12) ),

  tot_rk_1  = rk_1  + btl_rk_1 ,
  tot_rk_2  = rk_2  + btl_rk_2 ,
  tot_rk_3  = rk_3  + btl_rk_3 ,
  tot_rk_4  = rk_4  + btl_rk_4 ,
  tot_rk_5  = rk_5  + btl_rk_5 ,
  tot_rk_6  = rk_6  + btl_rk_6 ,
  tot_rk_7  = rk_7  + btl_rk_7 ,
  tot_rk_8  = rk_8  + btl_rk_8 ,
  tot_rk_9  = rk_9  + btl_rk_9 ,
  tot_rk_10 = rk_10 + btl_rk_10,
  tot_rk_11 = rk_11 + btl_rk_11,
  tot_rk_12 = rk_12 + btl_rk_12;

# Dapatkan persen2 keuangan
UPDATE target_realisasi_pd
  SET 
  tot_tkp_1  = (tot_tk_1  / anggaran_total) * 100,
  tot_tkp_2  = (tot_tk_2  / anggaran_total) * 100,
  tot_tkp_3  = (tot_tk_3  / anggaran_total) * 100,
  tot_tkp_4  = (tot_tk_4  / anggaran_total) * 100,
  tot_tkp_5  = (tot_tk_5  / anggaran_total) * 100,
  tot_tkp_6  = (tot_tk_6  / anggaran_total) * 100,
  tot_tkp_7  = (tot_tk_7  / anggaran_total) * 100,
  tot_tkp_8  = (tot_tk_8  / anggaran_total) * 100,
  tot_tkp_9  = (tot_tk_9  / anggaran_total) * 100,
  tot_tkp_10 = (tot_tk_10 / anggaran_total) * 100,
  tot_tkp_11 = (tot_tk_11 / anggaran_total) * 100,
  tot_tkp_12 = (tot_tk_12 / anggaran_total) * 100,

  tot_rkp_1  = (tot_rk_1  / anggaran_total) * 100,
  tot_rkp_2  = (tot_rk_2  / anggaran_total) * 100,
  tot_rkp_3  = (tot_rk_3  / anggaran_total) * 100,
  tot_rkp_4  = (tot_rk_4  / anggaran_total) * 100,
  tot_rkp_5  = (tot_rk_5  / anggaran_total) * 100,
  tot_rkp_6  = (tot_rk_6  / anggaran_total) * 100,
  tot_rkp_7  = (tot_rk_7  / anggaran_total) * 100,
  tot_rkp_8  = (tot_rk_8  / anggaran_total) * 100,
  tot_rkp_9  = (tot_rk_9  / anggaran_total) * 100,
  tot_rkp_10 = (tot_rk_10 / anggaran_total) * 100,
  tot_rkp_11 = (tot_rk_11 / anggaran_total) * 100,
  tot_rkp_12 = (tot_rk_12 / anggaran_total) * 100,

  tot_rkp_1_dev  = ( (tot_rk_1  / anggaran_total) * 100 ) - ( (tot_tk_1  / anggaran_total) * 100 ),
  tot_rkp_2_dev  = ( (tot_rk_2  / anggaran_total) * 100 ) - ( (tot_tk_2  / anggaran_total) * 100 ),
  tot_rkp_3_dev  = ( (tot_rk_3  / anggaran_total) * 100 ) - ( (tot_tk_3  / anggaran_total) * 100 ),
  tot_rkp_4_dev  = ( (tot_rk_4  / anggaran_total) * 100 ) - ( (tot_tk_4  / anggaran_total) * 100 ),
  tot_rkp_5_dev  = ( (tot_rk_5  / anggaran_total) * 100 ) - ( (tot_tk_5  / anggaran_total) * 100 ),
  tot_rkp_6_dev  = ( (tot_rk_6  / anggaran_total) * 100 ) - ( (tot_tk_6  / anggaran_total) * 100 ),
  tot_rkp_7_dev  = ( (tot_rk_7  / anggaran_total) * 100 ) - ( (tot_tk_7  / anggaran_total) * 100 ),
  tot_rkp_8_dev  = ( (tot_rk_8  / anggaran_total) * 100 ) - ( (tot_tk_8  / anggaran_total) * 100 ),
  tot_rkp_9_dev  = ( (tot_rk_9  / anggaran_total) * 100 ) - ( (tot_tk_9  / anggaran_total) * 100 ),
  tot_rkp_10_dev = ( (tot_rk_10 / anggaran_total) * 100 ) - ( (tot_tk_10 / anggaran_total) * 100 ),
  tot_rkp_11_dev = ( (tot_rk_11 / anggaran_total) * 100 ) - ( (tot_tk_11 / anggaran_total) * 100 ),
  tot_rkp_12_dev = ( (tot_rk_12 / anggaran_total) * 100 ) - ( (tot_tk_12 / anggaran_total) * 100 );
   
SELECT * FROM target_realisasi_pd;

SELECT 
  @anggaran_total AS anggaran_total_kota,
  @anggaran_bl AS anggaran_bl_kota,
  @anggaran_btl AS anggaran_btl_kota,

  SUM( (anggaran_total / @anggaran_total)  * tot_tf_1 ) AS target_fisik_kota_1 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_2 ) AS target_fisik_kota_2 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_3 ) AS target_fisik_kota_3 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_4 ) AS target_fisik_kota_4 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_5 ) AS target_fisik_kota_5 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_6 ) AS target_fisik_kota_6 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_7 ) AS target_fisik_kota_7 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_8 ) AS target_fisik_kota_8 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_9 ) AS target_fisik_kota_9 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_10) AS target_fisik_kota_10,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_11) AS target_fisik_kota_11,
  SUM( (anggaran_total / @anggaran_total)  * tot_tf_12) AS target_fisik_kota_12,

  SUM( (anggaran_total / @anggaran_total)  * tot_rf_1 ) AS realisasi_fisik_kota_1 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_2 ) AS realisasi_fisik_kota_2 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_3 ) AS realisasi_fisik_kota_3 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_4 ) AS realisasi_fisik_kota_4 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_5 ) AS realisasi_fisik_kota_5 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_6 ) AS realisasi_fisik_kota_6 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_7 ) AS realisasi_fisik_kota_7 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_8 ) AS realisasi_fisik_kota_8 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_9 ) AS realisasi_fisik_kota_9 ,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_10) AS realisasi_fisik_kota_10,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_11) AS realisasi_fisik_kota_11,
  SUM( (anggaran_total / @anggaran_total)  * tot_rf_12) AS realisasi_fisik_kota_12,

  SUM(tot_tk_1 ) AS target_keuangan_kota_1 ,
  SUM(tot_tk_2 ) AS target_keuangan_kota_2 ,
  SUM(tot_tk_3 ) AS target_keuangan_kota_3 ,
  SUM(tot_tk_4 ) AS target_keuangan_kota_4 ,
  SUM(tot_tk_5 ) AS target_keuangan_kota_5 ,
  SUM(tot_tk_6 ) AS target_keuangan_kota_6 ,
  SUM(tot_tk_7 ) AS target_keuangan_kota_7 ,
  SUM(tot_tk_8 ) AS target_keuangan_kota_8 ,
  SUM(tot_tk_9 ) AS target_keuangan_kota_9 ,
  SUM(tot_tk_10) AS target_keuangan_kota_10,
  SUM(tot_tk_11) AS target_keuangan_kota_11,
  SUM(tot_tk_12) AS target_keuangan_kota_12,

  (SUM(tot_tk_1 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_1 ,
  (SUM(tot_tk_2 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_2 ,
  (SUM(tot_tk_3 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_3 ,
  (SUM(tot_tk_4 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_4 ,
  (SUM(tot_tk_5 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_5 ,
  (SUM(tot_tk_6 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_6 ,
  (SUM(tot_tk_7 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_7 ,
  (SUM(tot_tk_8 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_8 ,
  (SUM(tot_tk_9 ) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_9 ,
  (SUM(tot_tk_10) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_10,
  (SUM(tot_tk_11) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_11,
  (SUM(tot_tk_12) / @anggaran_total ) * 100 AS target_keuangan_kota_persen_12, 

  SUM(tot_rk_1 ) AS realisasi_keuangan_kota_1 ,
  SUM(tot_rk_2 ) AS realisasi_keuangan_kota_2 ,
  SUM(tot_rk_3 ) AS realisasi_keuangan_kota_3 ,
  SUM(tot_rk_4 ) AS realisasi_keuangan_kota_4 ,
  SUM(tot_rk_5 ) AS realisasi_keuangan_kota_5 ,
  SUM(tot_rk_6 ) AS realisasi_keuangan_kota_6 ,
  SUM(tot_rk_7 ) AS realisasi_keuangan_kota_7 ,
  SUM(tot_rk_8 ) AS realisasi_keuangan_kota_8 ,
  SUM(tot_rk_9 ) AS realisasi_keuangan_kota_9 ,
  SUM(tot_rk_10) AS realisasi_keuangan_kota_10,
  SUM(tot_rk_11) AS realisasi_keuangan_kota_11,
  SUM(tot_rk_12) AS realisasi_keuangan_kota_12,

  (SUM(tot_rk_1 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_1 ,
  (SUM(tot_rk_2 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_2 ,
  (SUM(tot_rk_3 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_3 ,
  (SUM(tot_rk_4 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_4 ,
  (SUM(tot_rk_5 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_5 ,
  (SUM(tot_rk_6 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_6 ,
  (SUM(tot_rk_7 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_7 ,
  (SUM(tot_rk_8 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_8 ,
  (SUM(tot_rk_9 ) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_9 ,
  (SUM(tot_rk_10) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_10,
  (SUM(tot_rk_11) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_11,
  (SUM(tot_rk_12) / @anggaran_total ) * 100 AS realisasi_keuangan_kota_persen_12 

FROM target_realisasi_pd