<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Test_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get program by kode_prog
     */
    function get_test($id_test)
    {
      return $this->db->get_where('test',array('id_test'=>$id_test))->row_array();
     } 

    /*
     * Get all program
     */
    function get_all_test($id_test)
    {
        //$this->db->select('a.*, b.nama_giat');
        $this->db->from('test as a');
        //$this->db->join('kegiatan as b', 'a.id_test = b.id_test');
        $this->db->where(array('a.id_test'=>$id_test));
        return $this->db->get()->result_array();
        //return $this->db->get_where('program',array('kode_pd'=>$kode_pd))->result_array();
    }

    /*
     * function to add new program
     */
    function add_test($params)
    {
        $this->db->insert('test',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update program
     */
    function update_test($id_test,$params)
    {
        $this->db->where('id_test',$id_test);
        $response = $this->db->update('test',$params);
        if($response)
        {
            return "program updated successfully";
        }
    else
    {
        return "Error occuring while updating program";
    }
}

    /*
     * function to delete program
     */
    function delete_test($id_test)
    {
        $response = $this->db->delete('test',array('id_test'=>$id_test));
        if($response)
        {
            return "program deleted successfully";
        }
    else
    {
        return "Error occuring while deleting program";
    }
}

}
